### ISSUE TITLE
Allow games to be updated

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#1]
Currently Minigalaxy doesn't support updating games yet

**Comment by sharkwouter** [comment]
Some input on how the user should be shown that there is an update and if the previous version should be preserved.

**Comment by springbov** [comment]
One idea for how this could be accomplished. In the picture representing the game, if an update is available, replace the gear icon with something like a yellow up arrow, or perhaps some other symbol.

That could help identify the update.

The option to update could just be added to that gear menu.

**Comment by sharkwouter** [comment]
That's pretty good. I should probably make it green then and just show the same menu with an update option added to it.

Btw, are you running Minigalaxy in dark mode? I wasn't sure if that would work tbh

**Comment by springbov** [comment]
I have my system set up via the gnome tweak tool to have every application in dark mode. It's the Adwaita Dark. I hadn't gone in and specifically set mini galaxy to dark mode.

However, I can say, it looks great. I haven't had any 'can't see the text' or such issues.
