### ISSUE TITLE
More game details

### ISSUE THREAD

**Issue by metafarion** [sharkwouter/minigalaxy#106]
Another one for the pile of feature requests: Additional details on each game accessible via the game list interface.  Right now the UI is pretty sparse; each game has a title image and a Download/Play button and that's basically it.  It would be helpful to have actual text titles (as the images are not always super-legible), as well as game descriptions, ratings, etc.  Perhaps that much detail warrants a "Details" view for each game to keep the UI from getting too cluttered.  If this is a ton of work to implement, even a link to each game's page at GOG.com would be useful.  After all, we game hoarders don't necessarily remember what every game in our library is about.

**Comment by sharkwouter** [comment]
Thanks for reporting. I think this is a good idea, but keeping the UI clean as well would be a priority here.

I see two ways this can be implemented:
- Adding a list view, pretty much like you describe. This would require creating a second library class in ``minigalaxy/ui/``, which should probably extend some library base class. That way we can later add more views. This would require some way to reuse the gametile code as well, it's quite the coding challenge.
- Adding a details/properties button to the game specific menu which currently allows you to uninstall, open files and open the support page. This should then open a window which shows additional information.

**Comment by metafarion** [comment]
I like that there's are Store Page and Support links on each game now, but it'd be nicer if it were available on all games, not just the ones that are currently installed.

**Comment by sharkwouter** [comment]
That's a good point, thanks!

**Comment by makson96** [comment]
I see that I can now go to store page of uninstalled game:
![uninstall_store](https://user-images.githubusercontent.com/1833284/113819747-088a0780-977a-11eb-9e61-b7477183a4cd.png)
Is this issue done? If not, what is the objective now?

**Comment by sharkwouter** [comment]
I would say it is not quite done yet. I see this is a request for extra information in the properties window.

**Comment by sharkwouter** [comment]
The properties window has been updated on master to include more information
