### ISSUE TITLE
[Enhancement] Ability to add command prefix

### ISSUE THREAD

**Issue by spannerman79** [sharkwouter/minigalaxy#108]
This is handy/useful if you wish to use MangoHUD for FPS etc

See https://github.com/flightlessmango/MangoHud#normal-usage

**Comment by sharkwouter** [comment]
Good idea. I'll put this on the backlog. I'm planning on making a small settings screen which allows you to configure things like this and see some additional information about the game. This would fit right in with that.

**Comment by sharkwouter** [comment]
This has been added on master
