### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [sharkwouter/minigalaxy#11]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Minigalaxy on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by sharkwouter** [comment]
I would love to, but I have no experience making flatpaks. I'll look into it when I've resolved some of the high priority issues.

Help with packaging for other systems would be welcome as well :)

**Comment by ProTheory8** [comment]
I think I can try to help with this one, I've packaged some apps into Flatpak before.

**Comment by sharkwouter** [comment]
Minigalaxy has been on Flathub for a while, but I forgot to close this issue.
