### ISSUE TITLE
Unpacked content broken due missing symlinks

### ISSUE THREAD

**Issue by tim77** [sharkwouter/minigalaxy#113]
Content which installed by original GOG installer or unpacked by `unzip` utility:

- [Normal](https://gist.githubusercontent.com/tim77/aaf5af847a1477aeb999f3f9e72b1027/raw/35b7754257bf722cee9fd5208affc0dcf4b218f2/minigalaxy)

Content which unpacked by `minigalaxy`:

- [minigalaxy](https://gist.githubusercontent.com/tim77/0e2a1c7b24b79c2aa93e3ac33ad17914/raw/7c35c53338780bdfaa02ece2b18dc9eb4b868d97/minigalaxy%2520broken)

What can cause this? `zipfile` python module? This a reason why we got this error [here](https://github.com/flathub/flathub/pull/1402#issuecomment-606659889).

**Comment by sharkwouter** [comment]
What happens if you unpack with the unzip command? Minigalaxy used to use unzip in the first version, because the zipfile library doesn't preserve permissions. I've since found a workaround for that, but going back to unzip can be done if it preserves symlinks better.

**Comment by gasinvein** [comment]
So `unzip` doesn't preserve permissions, while python's `ZipFile` doesn't preserve symlinks? Maybe use `bsdtar`, then? Or even add a UI switch to select extraction method.

**Comment by sharkwouter** [comment]
No, python requires some extra work to preserve permissions. Unzip does permissions just fine. I would like to know how unzip deals with symlinks.

**Comment by gasinvein** [comment]
Hm, looks like `unzip` does preserve symlinks, but exists with status 1.

**Comment by sharkwouter** [comment]
I've now replaced the use of zipfile with the unzip command. This should be solved now.
