### ISSUE TITLE
Disable showing Wine games switch if wine is not installed

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#114]
Currently you can enable showing Windows games even if wine is not installed. This can cause confusion. The switch to enable this is settings should not be usable if wine is unavailable.

**Comment by sharkwouter** [comment]
Solved with 5479ce92ef55cd9f251efcedd1350981b72882ec

**Comment by arrowgent** [comment]
i kind of dont like this option to force it off.

if you could give a popup window warning why this is disabled and allowing the user to enable it (in big red letters)

otherwise i just edit the config.json to allow me to see the games.
