### ISSUE TITLE
Update translations for 0.9.4 release

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#115]
It would be great if the following translations could be updated before the 0.9.4 release happens on the 20th of April:

- [x] de.po
- [x] fr.po
- [x] nb_NO.po
- [x] nl.po (assigned to @sharkwouter)
- [x] nn_NO.po
- [x] pl.po
- [x] pt_BR.po
- [x] ru_RU.po
- [x] tr.po
- [x] zh_TW.po

I'll ping all the translators and update this issue when translations have been updated.

**Comment by sharkwouter** [comment]
@BlindJerobine, @thomasb22, @LordPilum, @kimmalmo, @ArturWroblewski, @EsdrasTarsis, @protheory8, @fuzunspm and @s8321414, would you guys be willing to help out again? This release shouldn't have to many string changes. I'll not add any new strings until after the release from now on, so the translations will not go out of date again before then.

**Comment by ArturWroblewski** [comment]
No problem "pl.po" will be done on time.

**Comment by s8321414** [comment]
zh_TW.po done in #121 :smiley:

**Comment by sharkwouter** [comment]
You guys are so fast, I'm amazed :o

**Comment by fuzunspm** [comment]
i did a PR for turkish translation

**Comment by sharkwouter** [comment]
Thanks! I've merged it

**Comment by thomasb22** [comment]
I don't have anything to add for the French translation, right?

**Comment by sharkwouter** [comment]
@thomasb22 there are 4 new strings which haven't been translated yet:
```
#: minigalaxy/ui/preferences.py:47
msgid "Install Wine to enable this feature"
msgstr ""

#. Open winecfg settings for Windows games
#: data/ui/gametile.ui:59
msgctxt "Wine Settings"
msgid "Settings"
msgstr ""

#. Open store page
#: data/ui/gametile.ui:17
msgctxt "store"
msgid "Store Page"
msgstr ""

#: data/ui/preferences.ui:198
msgctxt "show_windows_games_tooltip"
msgid "Whether Windows games are shown in the library or not"
msgstr ""
```
You can used the ``scripts/missing-translations.sh`` script to check. It gives a list for all languages, though, so it is a little bit hard to read.

**Comment by thomasb22** [comment]
Oops, sorry, my repository wasn't up to date. It's done now and I've update french translate 👍

**Comment by sharkwouter** [comment]
Thanks! I've merged it

**Comment by sharkwouter** [comment]
Thanks for all the pull requests guys! All translations are now complete! I'll compile them and update the changelog
