### ISSUE TITLE
Temporary extracted files and installers may stay in some conditions

### ISSUE THREAD

**Issue by tim77** [sharkwouter/minigalaxy#119]
Hello. :) I have found one another pretty unpleasant bug. Story: i have changed installation path for installed games which located on HDD. Then i queued for downloading couple of games and was AFK. When i back after some time a have seen that there was not free space on HDD ("Installation path") and whole downloading processes goes wrong. Zero free space on HDD is not the biggest problem there IMO, the problem is that temporary files in `cache/minigalaxy/extract` and many installers in `cache/minigalaxy/download` folder not auto cleaned and ate **tons** of space (on SSD).

For users this could be not obvious and would be nice if Minigalgaxy can handle this somehow. Maybe at least we should have some nice button in GUI to clean such trashy files.

**Comment by sharkwouter** [comment]
Odd, this is a bug actually. Those files should be deleted afterinstallation. Thanks for reporting!

**Comment by sharkwouter** [comment]
This should be resolved in the next release which is coming up this weekend.
