### ISSUE TITLE
Grim Fandango is borked after installation

### ISSUE THREAD

**Issue by radek-sprta** [sharkwouter/minigalaxy#127]
After installing Grim Fandango in Minigalaxy, it fails with the following error:

Running Grim Fandango Remastered
./GrimFandango: error while loading shared libraries: /home/dak/GOG Games/GrimFandangoRemastered/game/bin/i386/usr/lib/i386-linux-gnu/libGLU.so.1: file too short

As far as I could tell, libGLU.so.1 should be a symlink to libGLU.so.1.3.08004. Instead, it is a regular file with "libGLU.so.1.3.08004" as contents. Same goes for all other libraries in the directory.

I didn't see such behavior using the official GOG installer, so I thought I'd report it as a potential bug. If it doesn't have anything to do with Minigalaxy, feel free to close this issue.

**Comment by sharkwouter** [comment]
I think this is related to #113. Would it be possible for you to test the installation of Grim Fandango again with the latest commits in master? Do do so, look [here](https://github.com/sharkwouter/minigalaxy#installation) under other distributions.

**Comment by radek-sprta** [comment]
Yea, that solves it. Sorry, should have taken a better look at past issues!

**Comment by sharkwouter** [comment]
Thanks for testing! Don't worry about it, I'm glad someone tested it
