### ISSUE TITLE
Windows Installation Support "Bug"

### ISSUE THREAD

**Issue by Glog78** [sharkwouter/minigalaxy#134]
Hello,

thank you for supporting local wine Installations. I found a ?small? bug and want to report it.

Example Game:
"Omikron: Nomad Souls"

Because of the ":" the installer complains about a wrong preselected path. I supose if i change the path the runner might have troubles to run the game (didn't test further). Maybe the path should be cleaned up a little further.

**Comment by sharkwouter** [comment]
I see, I had forfotten about this. Thanks for the report!

**Comment by sharkwouter** [comment]
This should be fixed on master now. Could you test it?

**Comment by Glog78** [comment]
Tested with the latest git. Works now :) Thank you

**Comment by sharkwouter** [comment]
Great! Thanks for testing
