### ISSUE TITLE
[Feature Request] Download Rate Limiter

### ISSUE THREAD

**Issue by JoshuaFern** [sharkwouter/minigalaxy#136]
Folks with inadequate internet may benefit greatly from the ability to limit download rates, enabling them to continue to use the web as usual by setting an upper limit to the download speed.

Particularly affected are playing online games or watching/broadcasting a livestream.

**Comment by sharkwouter** [comment]
Fortunately, this is not a situation which applies to me, making it rank not very high on my priority list. Maybe somebody else would be interested in implementing it.

**Comment by JoshuaFern** [comment]
Closing as this has gone stale.
