### ISSUE TITLE
problem with game folder name (wine)

### ISSUE THREAD

**Issue by sneekee-stache** [sharkwouter/minigalaxy#137]
some games with wine can't be installed because of the folder names
like blood:fresh supply because gog installer don't like the ":" in the folder name
it could be fix by having another folder where the game is installed but i prefer only having one folder for the game instead of 2.

**Comment by sharkwouter** [comment]
Thanks for reporting. This seems to be the same issues as#134

**Comment by sharkwouter** [comment]
This should be fixed on master now
