### ISSUE TITLE
i am having a error after install it on linux mint

### ISSUE THREAD

**Issue by skarmiglione** [sharkwouter/minigalaxy#138]
Hello, i did install the deb to my linux mint, and i am having this log, what did i do wrong?

minigalaxy 
Traceback (most recent call last):
  File "/usr/games/minigalaxy", line 66, in <module>
    main()
  File "/usr/games/minigalaxy", line 57, in main
    from minigalaxy.ui import Window
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/__init__.py", line 2, in <module>
    from minigalaxy.ui.window import Window
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/window.py", line 5, in <module>
    from minigalaxy.ui.login import Login
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/login.py", line 12, in <module>
    @Gtk.Template.from_file(os.path.join(UI_DIR, "login.ui"))
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 137, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_games_minigalaxy.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/games/minigalaxy", line 66, in <module>
    main()
  File "/usr/games/minigalaxy", line 57, in main
    from minigalaxy.ui import Window
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/__init__.py", line 2, in <module>
    from minigalaxy.ui.window import Window
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/window.py", line 5, in <module>
    from minigalaxy.ui.login import Login
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/login.py", line 12, in <module>
    @Gtk.Template.from_file(os.path.join(UI_DIR, "login.ui"))
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 137, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'

**Comment by sharkwouter** [comment]
I think your version of Linux Mint might be based on Ubuntu 18.04, which does not have python3-gi version 3.30 or newer. Could you post the output of ``apt-cache show python3-gi``?

If the version is lower than 3.30, there might be a bug in the package as well, since it shouldn't install in that case.

**Comment by skarmiglione** [comment]
Package: python3-gi
Architecture: amd64
Version: 3.26.1-2ubuntu1
Priority: important
Section: python
Source: pygobject
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 630
Depends: python3 (<< 3.7), python3 (>= 3.6~), python3:any (>= 3.3.2-2~), libc6 (>= 2.14), libffi6 (>= 3.0.4), libgirepository-1.0-1 (>= 1.44.0), libglib2.0-0 (>= 2.41.1), gir1.2-glib-2.0 (>= 1.39.0)
Filename: pool/main/p/pygobject/python3-gi_3.26.1-2ubuntu1_amd64.deb
Size: 153080
MD5sum: f3ceafd931560ade4151d31ba790b6bb
SHA1: 9aca89bd927a66353b66f8463237be4cee9aaa86
SHA256: 3e7771eb3acb2e8b98f34f839f046e0c3382c3b115c6f4afc991bf801f0531ed
Homepage: https://wiki.gnome.org/Projects/PyGObject
Description-es: Python 3 bindings for gobject-introspection libraries
 GObject es una capa de abstracción que permite programar con un paradigma
 de orientación a objetos que es compatible con muchos lenguajes. Es parte
 de Glib, la biblioteca principal que se usa para generar GTK+ y GNOME.
 .
 This package contains the Python 3 binding generator for libraries that
 support gobject-introspection, i. e. which ship a gir1.2-<name>-<version>
 package. With these packages, the libraries can be used from Python 3.
Description-md5: f0850471c776a975236399e3050363aa
Task: minimal
Supported: 5y

Package: python3-gi
Architecture: amd64
Version: 3.26.1-2
Priority: important
Section: python
Source: pygobject
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 630
Depends: python3 (<< 3.7), python3 (>= 3.6~), python3:any (>= 3.3.2-2~), libc6 (>= 2.14), libffi6 (>= 3.0.4), libgirepository-1.0-1 (>= 1.44.0), libglib2.0-0 (>= 2.41.1), gir1.2-glib-2.0 (>= 1.39.0)
Filename: pool/main/p/pygobject/python3-gi_3.26.1-2_amd64.deb
Size: 153240
MD5sum: d689789d7751d4334893a5343e0f28f1
SHA1: 79ca2d40a836caf25223ddcb77386f9f25f0463f
SHA256: f12891060d6851adc12b31147bd9b6379dc8d36ff2f9ebda383d1c2eebebad8f
Homepage: https://wiki.gnome.org/Projects/PyGObject
Description-es: Python 3 bindings for gobject-introspection libraries
 GObject es una capa de abstracción que permite programar con un paradigma
 de orientación a objetos que es compatible con muchos lenguajes. Es parte
 de Glib, la biblioteca principal que se usa para generar GTK+ y GNOME.
 .
 This package contains the Python 3 binding generator for libraries that
 support gobject-introspection, i. e. which ship a gir1.2-<name>-<version>
 package. With these packages, the libraries can be used from Python 3.
Description-md5: f0850471c776a975236399e3050363aa
Task: minimal
Supported: 5y

**Comment by sharkwouter** [comment]
Yeah, that's too old, unfortunately. You won't be able to run Minigalaxy :(

Did you have any issues installing Minigalaxy?

**Comment by sharkwouter** [comment]
I'm going to close this for now. This seems to be an installation on an unsupported version of Mint.
