### ISSUE TITLE
Error after Wine game installation, game unplayable

### ISSUE THREAD

**Issue by JeffRockatansky** [sharkwouter/minigalaxy#141]
Distribution: Pop!_OS 19.10
Minigalaxy version: 0.9.4
Problem: After I install a Wine game, just before progress bar completion and Installer closing there are some errors:
![Screenshot from 2020-04-25 13-04-24](https://user-images.githubusercontent.com/26058495/80283885-71789b00-8734-11ea-92fe-c8eb92aacd9f.png)
![Screenshot from 2020-04-25 13-34-12](https://user-images.githubusercontent.com/26058495/80283887-73425e80-8734-11ea-86d9-6922a9f7dc50.png)
![Screenshot from 2020-04-25 13-34-27](https://user-images.githubusercontent.com/26058495/80283888-73daf500-8734-11ea-9686-16c405fc864d.png)
![Screenshot from 2020-04-25 13-34-51](https://user-images.githubusercontent.com/26058495/80283889-74738b80-8734-11ea-8de9-cdc59c4a8bd9.png)
Installer is reporting successful installation if I close the errors. It is even registered as installed in minigalaxy library UI. But game is unplayable, it crashes every launch.

Game tested: Pathologic 2 (made on Unity)

**Comment by SvdB-nonp** [comment]
These errors are probably not related to your issue, as they will almost always pop-up for GOG installations, even when installation is succesful.
Hiding these pop-ups (but keep them logged?) in the future would be my suggestion, so they don't give people the wrong idea about whether the outcome failed or not.

To actually debug your game, try to run minigalaxy from console. If that doesn't give any error, try to run the application manually:
WINEPREFIX=<path_to_gamefolder>/prefix wine <path_to_gamefolder>/<Pathologic2_executable>

This may give you the console output you need to debug the game.

**Comment by sharkwouter** [comment]
I see these errors as well, but I don't have issues playing most games. It could be a compatibility issue with this specific game. Do you know if it works in wine when installed in another way?

**Comment by JeffRockatansky** [comment]
> Do you know if it works in wine when installed in another way?
Pathologic 2 is [Gold on ProtonDB](https://www.protondb.com/app/505230), runs on Steam Play.

In my case (GOG, Wine) it has some errors about access to RAM pages.

**Comment by SvdB-nonp** [comment]
I have the game myself, so I just tried it myself. Got the same error popups (as expected) and then the game launches fine. This is on Solus-Gnome/AMD-RX580.

If you don want to debug in the terminal, maybe you can try alt-tab to see if there is a wine-crash popup error. With some fiddling (alt-tab followed by arrow+space) you might even open the details of it.

[offtopic]
It's offtopic, but for me the game runs very poorly, even with DXVK. Just wanted to mention this, before you spend way too much time debugging your issue to find out you cannot play it comfortably anyway.
Maybe proton does something to fix it, which can explain the gold rating. The very slow exit mentioned at protondb is btw not a wine issue, that is the case (for me at least) on windows as well.

**Comment by sharkwouter** [comment]
Some fixes have been made on the master branch. Could you test again? The errors may still pop up, but it might work now.

**Comment by IroAlexis** [comment]
Hello, I allow myself to report that this problem can be closed.
Indeed it was a Wine problem that is fixed since Wine 5.18 https://bugs.winehq.org/show_bug.cgi?id=49591

**Comment by sharkwouter** [comment]
Great, thanks!
