### ISSUE TITLE
Duplicated games

### ISSUE THREAD

**Issue by DaiKaiser93** [sharkwouter/minigalaxy#142]
Apparently the client reads Demos and Full releases as the same game, so if you own the demo of a game and the full release (for example The Silver Case) appears as two entries.
 
It happens with upgrades too, after installing Wasteland 2 DC, it appears duplicated.
![Screenshot from 2020-04-26 01-41-49](https://user-images.githubusercontent.com/25765658/80302356-6e92a000-875e-11ea-8c89-98e2387e0789.png)
.

**Comment by sharkwouter** [comment]
Thanks for the report, I'll take a look at it

**Comment by sharkwouter** [comment]
It seems the GOG API does not distinguish between demos and full games. I was hoping the GOG website would provide a way to hide games, but it does not. I think the best solution for this would be to allow the user to hide specific games, but I'm not sure what this would look like. I've had a PR for this once before, but I was not a fan of the implementation at the time. Perhaps there is a better way of doing this, but if anyone wishes to build it please discuss the design with me first.

**Comment by sharkwouter** [comment]
I personally have not seen this issue pop up in the last couple of releases, so I'm going to close it.
