### ISSUE TITLE
Not listing all the games

### ISSUE THREAD

**Issue by PietJanHein** [sharkwouter/minigalaxy#146]
This GOG-client only shows 3 games, I have 6 or 7 installed including one of the XCom2 games and these games don't show up in the list. I don't know if this is a known problem.

**Comment by sharkwouter** [comment]
By default, no Windows games are shown. If you have Wine installed you can enable showing Windows games in the preferences menu.

**Comment by PietJanHein** [comment]
Thanks!

**Comment by sharkwouter** [comment]
No problem!
