### ISSUE TITLE
Wine install directory name handling

### ISSUE THREAD

**Issue by metafarion** [sharkwouter/minigalaxy#150]
If the install directory name is changed from within a GOG installer running via wine, the game files all go into the new directory, but the wine prefix and thumbnail image remain in a directory with the game's original title.  This is especially problematic for games that have characters in their Titles that Windows doesn't like, for example: colons.  This also confuses the Minigalaxy launcher regarding the location of the executable.

The case I originally encountered this issue in was Myst III: Exile.
Wine created the directory "\~/GOG Games/Myst III: Exile" The GOG installer would not allow me to install to that directory name because it contained an illegal character.  When I changed the install directory to "\~/GOG Games/Myst III - Exile" the install succeeded, but the wine prefix remained in the former directory whereas all the game file went into the latter directory.  Also Minigalaxy could not launch the game because it was expecting the executable in the original directory.

If possible, it might be advisable to run the GOG installer in some kind of "unattended" install, or not permit install directory changes at all since the wine prefix and the Minigalaxy launcher path seem to be set separately from the game's actual installer and things get weird if they don't match (even without the illegal character issue).

**Comment by metafarion** [comment]
A little research tells me that there are command-line switches you can use on GOG installers.  /silent skips the setup screen and just installs with default options.  /verysilent does the same thing without even showing an install progress window.  You can also pass an installation directory with /dir=, though that alone doesn't stop the user from altering it themselves.

**Comment by sharkwouter** [comment]
Does it also have an option to not install icons in combination with that? It sounds interesting, although you'd still see the wine prefix setup for a little bit.

**Comment by metafarion** [comment]
There is a /NOICONS switch, but it doesn't seem to do that exactly...
Here's the reference I've been looking at:
https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

**Comment by Zauberfisch** [comment]
I have also experienced issues with a game that has `:` in the title. `The Witcher 3: Wild Hunt - Game of the Year Edition`.

Here a detailed report:

1. during the install, the gog installer will force you to rename the folder (I chose `Witcher3`)
1. after install: 
   ```
   $ ls -1 ~/GOG\ Games
   'The Witcher 3: Wild Hunt - Game of the Year Edition'
   Witcher3
   ```
   `Witcher3` contains the actual game, the other folder only prefix and 1 thumbnail file.
1. attempting to start the game now through minigalaxy will error `No executable was found in ...`
1. after restarting minigalaxy, it now detects `Witcher3` as the game folder (I guess it scans the folders for the goggame-\d+.info file)
    (I think the `The Witcher 3: Wild Hunt - Game of the Year Edition` folder is now completely ignored)
1. attempting to start the game now will create a new wine prefix in `~/GOG\ Games/Witcher3/prefix` meaning the prefix exists twice now (the other one in the `The Witcher 3: Wild Hunt - Game of the Year Edition` folder
1. at this point I think the game would actually work, but there is another, unrelated bug stopping witcher 3 from working (#158)

**Comment by sharkwouter** [comment]
I'm going to close this issue in favor of #165. You should now always be able to install in the suggested directory on master. Some additional testing could be done for it, but it seems to be resolved now. Changing the installation directory to something outside the prefix is not something I would like to support when installing within the prefix works fine.
