### ISSUE TITLE
Flatpak version does not start (Locale not supported by C library.)

### ISSUE THREAD

**Issue by robschi** [sharkwouter/minigalaxy#151]
Hello,

I installed minigalaxy from flathub on my Debian testing, but unfortunately it does nocht start.
It says something about 'Locale not supported by C library.'.
I have Installed two language, en_US.UTF-8 and de_AT.UTF-8. Maybe it has something to do with this?

flatpak -v run io.github.sharkwouter.Minigalaxy 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/name/.local/share/flatpak
F: Opening user flatpak installation at path /home/name/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/name/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Allocated instance id 3967067839
F: Add defaults in dir /io/github/sharkwouter/Minigalaxy/
F: Add locks in dir /io/github/sharkwouter/Minigalaxy/
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/name/.config/pulse/client.conf': Error opening file /home/name/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 37 xdg-dbus-proxy --args=39'
F: Running 'bwrap --args 37 minigalaxy'

(minigalaxy:3): Gtk-WARNING **: 17:24:13.240: Locale not supported by C library.
        Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/app/bin/minigalaxy", line 66, in <module>
    main()
  File "/app/bin/minigalaxy", line 57, in main
    from minigalaxy.ui import Window
  File "/app/lib/python3.7/site-packages/minigalaxy/ui/__init__.py", line 2, in <module>
    from minigalaxy.ui.window import Window
  File "/app/lib/python3.7/site-packages/minigalaxy/ui/window.py", line 5, in <module>
    from minigalaxy.ui.login import Login
  File "/app/lib/python3.7/site-packages/minigalaxy/ui/login.py", line 8, in <module>
    from minigalaxy.translation import _
  File "/app/lib/python3.7/site-packages/minigalaxy/translation.py", line 7, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

`locale`
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE=de_AT.UTF-8
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Regards,
Robert

**Comment by sharkwouter** [comment]
Does this change if you change your system language? I've not seen this before, it may or may not be specific to flatpak. Another thing you could try is running without Flatpak, then we know if it's a Flatpak issue.

It might be related to https://github.com/sharkwouter/minigalaxy/issues/139, but probably not.

**Comment by robschi** [comment]
Yes, starting 'minigalaxy' after installing 'minigalaxy_0.9.4_all.deb' does work.
But I don't know if I want to change the system language :-D

**Comment by veribaka** [comment]
I am on the same boat as robschi:

```
flatpak run io.github.sharkwouter.Minigalaxy/x86_64/stable                                                      ─╯

(minigalaxy:2): Gtk-WARNING **: 12:22:51.777: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/app/bin/minigalaxy", line 66, in <module>
    main()
  File "/app/bin/minigalaxy", line 57, in main
    from minigalaxy.ui import Window
  File "/app/lib/python3.7/site-packages/minigalaxy/ui/__init__.py", line 2, in <module>
    from minigalaxy.ui.window import Window
  File "/app/lib/python3.7/site-packages/minigalaxy/ui/window.py", line 5, in <module>
    from minigalaxy.ui.login import Login
  File "/app/lib/python3.7/site-packages/minigalaxy/ui/login.py", line 8, in <module>
    from minigalaxy.translation import _
  File "/app/lib/python3.7/site-packages/minigalaxy/translation.py", line 7, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by tim77** [comment]
Probably [this](https://github.com/flathub/net.lutris.Lutris/issues/78#issuecomment-557873187).

**Comment by sharkwouter** [comment]
I'm closing this, because tim77 provided a fix for it in the comment above.
