### ISSUE TITLE
No indication when disk space is not sufficient

### ISSUE THREAD

**Issue by philthethrill100** [sharkwouter/minigalaxy#155]
I'm using an Acer Chromebook 15 that supports Linux Apps. I tried installing minigalaxy, and I got this error message: Error while installing package: cannot copy extracted data for './usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5.11.3' to '/usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5.11.3.dpkg-new'

**Comment by sharkwouter** [comment]
Which package was it? Do you have a link?

**Comment by philthethrill100** [comment]
I used this one. https://github.com/sharkwouter/minigalaxy/releases/download/0.9.4/minigalaxy_0.9.4_all.deb

**Comment by sharkwouter** [comment]
I think that may be unrelated. Try running ``sudo apt-get install -f`` to see if there is any existing dependency issue.

**Comment by philthethrill100** [comment]
I did that, and I used sudo apt-get autoremove like it suggested to remove any dependencies that weren't needed. I installed minigalaxy again, and it worked. I'm not able to install any of my games though. I get an error message saying that the games can't be unzipped.

**Comment by sharkwouter** [comment]
Good to hear that worked. Could you post the full error message here and check what the content is of files in ``~/.cache/minigalaxy/download``? If their file size is really small, you'll want to check to see if you're not getting html pages.

**Comment by philthethrill100** [comment]
It works now. I guess the problem was there wasn't enough storage space.

**Comment by sharkwouter** [comment]
Okay, this is related to #147 then.
