### ISSUE TITLE
Create Program Menu Shortcuts

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [sharkwouter/minigalaxy#156]
The normal GOG installation process asks if you would like to create application shortcuts. That functionality seems to be missing from minigalaxy. I miss it at least.

Looking inside my Fort Triumph folder, I see that there is a support/xdg-utils folder that has files for shortcut creation. And the icon is in the support folder.

**Comment by sharkwouter** [comment]
Thanks for reporting. I see there is some interest in this. It has been reported in #54 as well and is on my todo list. To keep this issue tracker clean, I will keep the old issue in favor of this one.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
Thanks. I searched for existing issues but did not find that one.
