### ISSUE TITLE
Gentoo Ebuild

### ISSUE THREAD

**Issue by metafarion** [sharkwouter/minigalaxy#16]
I'm interested in making this installable with Portage.  I've whipped up a basic Ebuild for 0.9.1 and I could conceivably do future releases if it's useful to you.

https://gist.github.com/metafarion/c66bf43243c00132a48e3346b083ec1f

**Comment by sharkwouter** [comment]
That would be great! Even better if you'd keep it updated. I wouldn't be able to make an Ebuild myself, since I'm not a Gentoo user.

**Comment by metafarion** [comment]
Alright, I'm in!  I'm a 20-year Gentoo vet, but this is my first Ebuild, so it's a learning opportunity for me.  Also, I'm still pretty inexperienced in GitHub stuff in general (I had to look up what a Gist was to give you that link above).  What would be the best way for me to contribute the ebuild?  Do you want it in the main project files?  Should I make it its own branch?  Its own project?  How does this all work?

**Comment by sharkwouter** [comment]
Cool, lets do this then! :)

You should probably maintain it in a seperate place, unless it is recommended to keep an Ebuild in the git repo of a piece of software, anyway. I will not be able to build the Gentoo package myself, so that will be up to you.

**Comment by metafarion** [comment]
Ok, I'll set up a portage overlay containing the ebuild as a separate project, and then you can just have in your docs "Gentoo users can install from THIS overlay, or download just the ebuild HERE"

**Comment by metafarion** [comment]
Alright, I think I'm just about ready to show this to the public.  The ebuilds for Minigalaxy can be found here: https://github.com/metafarion/metahax/tree/master/games-util/minigalaxy
Because of the way Gentoo handles packages though, it's often less work to add an overlay (repository) to your system and install from there than it is to install a single ebuild.  To that end, I've created an overlay called Metahax that can be installed here: https://github.com/metafarion/metahax

**Comment by sharkwouter** [comment]
Looks good, although I know nothing about Gentoo packages 😅

We can add some instructions for Gentoo to the README then :)

**Comment by metafarion** [comment]
For install instructions, I would just put "Available in the Metahax overlay" and link to https://github.com/metafarion/metahax.  I've put instructions and an install script there.  Installing portage overlays is a fairly common thing in Gentoo, similar to adding repos to sources.list in Debian.

**Comment by sharkwouter** [comment]
Instructions have been added to the README, thanks! Shall I keep this open until i686 support is in?

**Comment by metafarion** [comment]
Yeah, that's a good "completed" condition for this issue.  Let's leave it open.

**Comment by metafarion** [comment]
I have now done some basic testing in an i686 environment; I believe this is ready for prime time.  Or at least for user feedback :-P

**Comment by sharkwouter** [comment]
Awesome! Then I'll close the issue. Will reopen if any issues are reported.
