### ISSUE TITLE
Any plan for integrations/other stores? (Galaxy 2.0 feature)

### ISSUE THREAD

**Issue by jmtd** [sharkwouter/minigalaxy#166]
GOG Galaxy has added "Integrations", so it will show a merged game library from Gog and others (Steam, Epic, not sure what else. Itch? Humble?). Is that on the roadmap or expressly out-of-scope for minigalaxy?

Thanks!

**Comment by sharkwouter** [comment]
At some point I was planning on doing this for GOG, but it's not really possible to integrate it well with a web application. The GOG API does not allow redirecting to a different URL, since it's only supposed to be for internal use.

**Comment by sharkwouter** [comment]
I'm closing this, because it is out of scope to add support for different stores.
