### ISSUE TITLE
Detecting Linux Game as Not Linux Compatable

### ISSUE THREAD

**Issue by MrHuggles** [sharkwouter/minigalaxy#167]
I'm not sure if this is or isn't a bug, but everything indicates that it likely is.  In the latest version of MiniGalaxy I've discovered that it doesn't detect a Linux game (Warlords 1 + 2 Collection - https://www.gog.com/game/warlords_i_ii) as a Linux game (lumping it in with windows titles and requiring Wine).  I'm not the most savvy of Linux users, but looking over the specs and having some help from a friend in troubleshooting this leaves me to believe that something might be buggy about how MiniGalaxy detects and sorts Linux titles from Windows titles.

I am currently using the latest version of Mint 20 (which seems to be built on Ubuntu 20.04, to the best of my research).

**Comment by sharkwouter** [comment]
That's odd, but I don't think I can test this, since I don't own this game. What you could do is launch Minigalax with the following command from a terminal and see if those games show up anywhere: ``MG_DEBUG=1 minigalaxy``

**Comment by MrHuggles** [comment]
> That's odd, but I don't think I can test this, since I don't own this game. What you could do is launch Minigalax with the following command from a terminal and see if those games show up anywhere: `MG_DEBUG=1 minigalaxy`

I just tried that and there was no difference in what it listed as a linux game.  If there's anything I can do to help you troubleshoot this problem/bug just let me know.

**Comment by MrHuggles** [comment]
I just made an interesting discovery.  When I go to my gog game library on the website and sort by filter (only display linux titles) the warlords game doesn't show up (only the games that mini galaxy displays for linux).  This might have to do with gog rather than mini galaxy.  I'll contact them and ask why a game listed as compatible with linux isn't showing up with the linux tab for filtering.  I'll let you know what they say.

**Comment by sharkwouter** [comment]
> > That's odd, but I don't think I can test this, since I don't own this game. What you could do is launch Minigalax with the following command from a terminal and see if those games show up anywhere: `MG_DEBUG=1 minigalaxy`
> 
> I just tried that and there was no difference in what it listed as a linux game. If there's anything I can do to help you troubleshoot this problem/bug just let me know.

My bad, but it doesn't change anything, it just prints the API responses in the terminal. It seems you found the reason for it already, though, I use the same API and filter as the GOG website I think.

**Comment by MrHuggles** [comment]
Sorry for the delayed response.  It took GOG ages (3 weeks) to get back to me and then I became distracted with life problems (all is good now, though).  In the end they say that they simply need to update their tags for the game, but don't know how long that will take (they are apparently short handed because of the pandemic).  I'm guessing that once they add/restore the linux tags the games will be detectable to mini Galaxy.

**Comment by sharkwouter** [comment]
Great, thanks for figuring this one out and clearing it up with GOG. I'll close it for now with the assumption that GOG will fix it. If this problem still exists after a month or so. A game specific fix could be added to Minigalaxy, but I'd rather not do that if it is not required.
