### ISSUE TITLE
I can't enable "Show Windows games"

### ISSUE THREAD

**Issue by Ahmed-E-86** [sharkwouter/minigalaxy#168]
I can't enable "Show Windows games" from preferences, it tells me to install Wine to enable this feature, but I have wine-staging installed on my system.

I use Kubuntu 20.04, and I installed Minigalaxy from Flatpak. Is that what causes this issue? Do I need to install WINE as Flatpak as well?

**Comment by Ahmed-E-86** [comment]
I installed the latest deb installer, and I didn't encounter this issue. It is kind of my fault, but how can I use Minigalaxy as Flatpak for research purposes?

**Comment by Ahmed-E-86** [comment]
I have more questions if you don't mind:
How can I use custom wine-prefix for any game?
How can I set pre-launch commands? (that will also help with the previous question)
Can I play Qwent without having to use GOG Galaxy launcher?

**Comment by sharkwouter** [comment]
Yeah, the flatpak doesn't currently support running Windows games unfortunately. Setting the wine version used could be useful, though, but currently it always uses the wine command available in your path.

**Comment by Ahmed-E-86** [comment]
I had a similar situation with Flatpak before, I installed fwupd from Flatpak, and Discover couldn't interact with it, so I installed fwupd from Snap instead, and they can interact with each others without any issues. I know that there a lot of people who hate Snap, but it is better in these situations.

Could you please answer my previous questions? That will help me a lot of getting a good view of what the application can do. Thanks in advance.

**Comment by sharkwouter** [comment]
To clarify, Minigalaxy just uses your system's wine to make prefixes and it does nothing special with them. There is currently a bug which breaks some Windows games, based on the name, but there is a PR to fix this. You can access the wine setting per game.

**Comment by arrowgent** [comment]
you can edit
```
/home/$USER/.config/minigalaxy/config.json
```
and force
```
"show_windows_games": true,
```

although if minigalaxy doesnt properly detect your wine, the "install" will fail
personally this is fine with me, i just want the full list of the games i own

**Comment by sharkwouter** [comment]
@arrowgent after thinking about this for a little while, I think you may be onto something. The user could also be shown an errorr message. This is not the highest priority right now, but I will put it on the list for 0.9.6

**Comment by Victor239** [comment]
> Yeah, the flatpak doesn't currently support running Windows games unfortunately.

Is this an issue with Minigalaxy itself, Flatpak or something else? Would like to see where I can track this issue.

**Comment by sharkwouter** [comment]
Flatpak cannot software installed on the system and the Minigalaxy flatpak package does not contain wine. That's why it doesn't work.

**Comment by Taffer** [comment]
Flatseal is a tool for mucking with Flatpak app permissions, including which bits of the host filesystem it can access, what environment variables are set, etc.  Maybe adding `/usr/bin` (or wherever your WINE lives) to the normal Flatpak app path would help?

I haven't had any luck yet, but I haven't dug up the Flatpak sandbox PATH setting. Setting it to `PATH=$PATH:/usr/bin` in Flatseal made Minigalaxy stop launching... I assume the sandbox isn't expanding the `$PATH` in there.

**Comment by sharkwouter** [comment]
The flatpak package has been updated to allow Windows games to be installed and a clearer error message was added for systems which do not have wine installed with the last release. I'd say this issue should have been resolved.
