### ISSUE TITLE
Minigalaxy not launching in Solus Plasma through the application launcher

### ISSUE THREAD

**Issue by paahtoleipae** [sharkwouter/minigalaxy#170]
When I launch Minigalaxy through the Plasma application menu it appears in the bottom panel for less than a second and then vanishes. I can launch Minigalaxy through the terminal and everything works, installing games and the like. This issue appeared when I reinstalled Solus; I was using Budgie before where I was using Minigalaxy completely normally.

What I've tried: reinstall, "minigalaxy --reset"

**Comment by sharkwouter** [comment]
Thanks for the report. Could you try running ``kde-open /usr/share/applications/io.github.sharkwouter.Minigalaxy.desktop`` to see if you get the same issue and if there is any output?

**Comment by paahtoleipae** [comment]
I don't have a program like that installed; "bash: kde-open: command not found". xdg-open opens the file and prints:

>kf5.kio.kdirmodel: protocol mismatch: "" vs "file"

**Comment by sharkwouter** [comment]
Odd, then I'm not sure what kde uses to launch desktop files. Maybe you can use gtk-launch instead.

**Comment by paahtoleipae** [comment]
beluga@beluga ~ $ gtk-launch minigalaxy
gtk-launch: no such application minigalaxy
beluga@beluga ~ $ eopkg info gtk-launch
gtk-launch package is not installed
gtk-launch package is not found in binary repositories
gtk-launch package is not found in source repositories
beluga@beluga ~ $ eopkg info kde-open
kde-open package is not installed
kde-open package is not found in binary repositories
kde-open package is not found in source repositories

**Comment by sharkwouter** [comment]
Damn, then I really don't know. I've not seen other reports of this. I would suggest you try the Solus package maintainer.

**Comment by paahtoleipae** [comment]
This is the output I get when I select "run in terminal" and "do not close when command exits" from the advanced options.

```
(minigalaxy:27211): Gtk-WARNING **: 15:09:19.724: Locale not supported by C library.
        Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/usr/bin/minigalaxy", line 66, in <module>
    main()
  File "/usr/bin/minigalaxy", line 57, in main
    from minigalaxy.ui import Window
  File "/usr/lib/python3.7/site-packages/minigalaxy/ui/__init__.py", line 2, in <module>
    from minigalaxy.ui.window import Window
  File "/usr/lib/python3.7/site-packages/minigalaxy/ui/window.py", line 5, in <module>
    from minigalaxy.ui.login import Login
  File "/usr/lib/python3.7/site-packages/minigalaxy/ui/login.py", line 8, in <module>
    from minigalaxy.translation import _
  File "/usr/lib/python3.7/site-packages/minigalaxy/translation.py", line 7, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by sharkwouter** [comment]
Now that is an error I can work with. I'll look into it on the weekend.

**Comment by SvdB-nonp** [comment]
Maybe it is an issue with language/format setup not the same language. I have the same thing with the Feral Launcher (Tomb Raider games) when I still used Solus Plasma, where "en_nl" (English language, but dutch time/date format) is not recognised and the launcher simply refuses to start. Setting the language and region to default english fixes that for the Feral launcher, so maybe that also works for this issue.

(As mentioned on Discord; on my other PC running Solus Plasma (full english formats) minigalaxy starts normally)

**Comment by sharkwouter** [comment]
Yeah, that could be. I should probably set a default locale in case it isn't set to something supported.

**Comment by paahtoleipae** [comment]
Yeah here are my settings:
Language: English (American)
Formats: Finland
Location: Sweden

**Comment by sharkwouter** [comment]
I think this may be fixed in master at the moment. Is there anyone here who can test if it no longer crashes when an unknown locale is used?

**Comment by SvdB-nonp** [comment]
I could see if I can test it on the PC with Plasma, assuming I can reproduce it, but can only do that coming weekend when I have some time.

**Comment by sharkwouter** [comment]
I'll close this for now and assume it will be resolved in the next release.
