### ISSUE TITLE
Not working on opensuse 15.2

### ISSUE THREAD

**Issue by MetaStazz** [sharkwouter/minigalaxy#179]
Opensuse 15.2, last kernel 5.3.18
KDE Plasma 5
Minigalxy 0.9.4 from Official Opensuse 15.2 Repo

As it was not specified that it will not work on opensuse 15.2, I tried!!
I can logging and than it's empty. It doesn't display anything !!
![Screenshot_20201001_203615](https://user-images.githubusercontent.com/20983400/94849733-2ae74500-0426-11eb-9ce9-4bb3f09e39e2.png)

It is said:
_"Minigalaxy does not ship for the following distributions because they do not contain the required version of PyGObject"_
In the package dependencies it say: _"python3-gobject >= 3.30"_ and I do have the 3.34.0 !!

**Almost......** ^^

**Comment by sharkwouter** [comment]
Do you have any games which officially support Linux? Try enabling displaying Windows games in settings.

**Comment by MetaStazz** [comment]
I do have some... I don't use windows games !!
But even without game it should display something right? (If not how to find and download game)

**Comment by sharkwouter** [comment]
Yeah, it only shows the games you own. You have to first buy games through the GOG website.
