### ISSUE TITLE
[Feature Request] Allow opening the store page of games which aren't installed

### ISSUE THREAD

**Issue by jianpan** [sharkwouter/minigalaxy#181]
First of all, Minigalaxy is great! I really appreciate your hard work.

Just wondering if you can add a feature to open GOG store page for the selected game? It's quite useful to check game information at GOG. Thanks!

**Comment by jianpan** [comment]
The release note mentioned this feature is included in 0.94. I'm using 0.94 from flathub but I couldn't find where is the Game Menu?

![image](https://user-images.githubusercontent.com/1950818/96349365-2739fc00-107d-11eb-9886-1473ad0e064a.png)

**Comment by sharkwouter** [comment]
![store-page](https://user-images.githubusercontent.com/5042659/96363763-7b54e700-1136-11eb-9daa-eefd2837c496.png)
 Here is an example of where you can find the store page link. It only applies to installed games, though.

**Comment by jianpan** [comment]
Got it. Thanks, sharkwouter. It would be nice to show this for uninstalled games as well. Sometimes I need to remind myself what the game is about before I install. :)

**Comment by sharkwouter** [comment]
No problem. Your proposal makes sense. I'll keep this one open and see when I'll get to it. It probably won't make it in the next release, though. Thanks for the report.

**Comment by breversa** [comment]
@sharkwouter : the "Store page" menu entry doesn't seem to appear reliably.

In addition to not showing on non-installed games (planned), it also doesn't appear for many of my games (e.g. Broforce, Hollow Knight, Wonderboy, etc.).

Or if it does, it's not always and I've been unable to establish a pattern so far.

**Comment by sharkwouter** [comment]
Thanks for the report @breversa. Unfortunately a small oversight caused this to stop working in version 1.0.0. The next version will have a fix for it.

**Comment by sharkwouter** [comment]
@breversa the issue you were having should've been resolved with version 1.0.1.

**Comment by breversa** [comment]
Sadly it doesn't work as of 1.0.1 : the settings icon doesn't appear on non-installed games :

![image](https://user-images.githubusercontent.com/2071276/104453560-e6cb1b00-55a4-11eb-946c-d38a92ea271a.png)

**Comment by sharkwouter** [comment]
My bad for not being clearer. This issue cannot be resolved yet, as we haven't worked on it yet, but you mentioned this additional issue:

> it also doesn't appear for many of my games (e.g. Broforce, Hollow Knight, Wonderboy, etc.).

I was wondering if that had been cleared up, since we did try to fix that one. Thanks!

**Comment by breversa** [comment]
The settings icon (with the link to the store page) appears on newly-installed games, but not on existing games.

If I delete then reinstall the game, the icon and the link appear correctly, so it's only an issue for pre-1.0.1 users. :)

**Comment by sharkwouter** [comment]
Thanks, I'll make another issue for this.

**Comment by makson96** [comment]
This seems to be done now. Right?
![uninstall_store](https://user-images.githubusercontent.com/1833284/113824471-25c1d480-9780-11eb-9291-b679ee7162f7.png)

**Comment by sharkwouter** [comment]
Good point, it is now implemented in master.
