### ISSUE TITLE
Full Throttle Remastered doesn't work after installing

### ISSUE THREAD

**Issue by berarma** [sharkwouter/minigalaxy#186]
The game's main data file `game/full.data` is split in two files after installation. The game crashes when launched.

This doesn't happen when installing with the installer downloaded from GOG.

The split files are:
```
-rw-r--r-- 1 berarma staff 4194304000 may 24  2018 full.data.split00
-rw-r--r-- 1 berarma staff 1270343297 may 24  2018 full.data.split01
```

The correct install has this file instead:
```
-rw------- 1 berarma staff 5464647297 nov 11 19:59 full.data
```

Using release 0.9.4.

**Comment by sharkwouter** [comment]
Thanks for the report, I'm really sorry for not noticing this issue sooner. Since this issue has been reported a couple of new versions have been released. Could you try again? Version 1.0.0 fixes a ton of similar issues.

**Comment by berarma** [comment]
Still the same. I've installed the latest version 1.0.0 but in the about window I'm still seeing 0.9.4. I'm pretty sure I have just one instance installed.

I guess the file is splitted to avoid some 4GB file size limit on the zip format and then the game installer joins the files on installation.

I'm a programmer with basic Python knowledge. I've taken a look at the Minigalaxy code and I don't see anywhere that handles joining the files or any processing that needs to be done on installation.

**Comment by sharkwouter** [comment]
Yeah, that's a bug. I forgot to change the version number in the 1.0.0 release.

I'm suprised by this issue, though. I've not seen this before. I'll take a look.

**Comment by berarma** [comment]
I've found `postinst.sh` and `preuninst.sh` scripts in `data/noarch/support/`.

The `postinst.sh` script joins the split files according to the contents of `data/noarch/support/split_files`. The `preuninst.sh` script removes the resulting file before uninstall, I guess because the uninstall script knows nothing about that file created by `postinst.sh`.

The scripts can be called from wherever since they change the working directory to the script directory and use relative paths from there. They call `yad`, a binary inside the support directory that displays a window with a progression bar while the files are joined.

**Comment by freaky-m0** [comment]
I have the same problem with "X4 Foundations". There is also a `postinst.sh` and `preuninst.sh` in `X4 Foundations/support/`. The game only runs after starting `postinst.sh` manually.

**Comment by sharkwouter** [comment]
Thanks for the reply. It's good to have some extra games to test this with.

**Comment by makson96** [comment]
Can anyone affected by this issue check if this branch solves problem:
https://github.com/sharkwouter/minigalaxy/pull/346

**Comment by sharkwouter** [comment]
This was fixed in the master branch and will be fixed in the next release

**Comment by berarma** [comment]
Thanks! It now works. It produces this messages in the log but nothing harmful it seems:

> full_throttle_remastered_en_gog_3_20993.sh integrity is preserved. MD5 is: 2f4bf151e225e7dfa9bec31ed49b721c
> error: End-of-centdir-64 signature not where expected (prepended bytes?)
>   (attempting to process anyway)
> warning [/home/berarma/.cache/minigalaxy/download/Full Throttle Remastered/full_throttle_remastered_en_gog_3_20993.sh]:  785566 extra bytes at beginning or within zipfile
>   (attempting to process anyway)

**Comment by sharkwouter** [comment]
Great! That error message is pretty standard, not much we can do about that. Happens with every game.
