### ISSUE TITLE
Update translation files for 1.0.0 release

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#187]
At this point so many fixes and additional features have been added, that the next release of Minigalaxy will be version 1.0.0. This release will happen on the 29th of November. For this the translations in Minigalaxy will need to be updated again, which is why I'll need some help again. Here is the list of translations:

- [x] de.po
- [ ] es.po
- [x] fr.po
- [x] nb_NO.po
- [x] nl.po
- [x] nn_NO.po
- [ ] pl.po
- [x] pt_BR.po
- [x] ru_RU.po
- [x] tr.po
- [x] zh_CN.po
- [x] zh_TW.po

**Comment by sharkwouter** [comment]
@BlindJerobine, @thomasb22, @LordPilum, @kimmalmo, @ArturWroblewski, @EsdrasTarsis, @protheory8, @fuzunspm, @s8321414, @juanborda and @dummyx, would you be willing to update the translations again? Let me know if the 30th of November is too soon as well, it is still possible to move the release out a bit.

**Comment by fuzunspm** [comment]
I sent PR for turkish

**Comment by ArturWroblewski** [comment]
Polish translation will be on time.

**Comment by s8321414** [comment]
I sent PR #192 :smiley:

**Comment by LordPilum** [comment]
#195

**Comment by thomasb22** [comment]
French translation is updated 😋 #196

**Comment by EsdrasTarsis** [comment]
#200 , btw congratulations on reaching 1.0.0 release :)

**Comment by sharkwouter** [comment]
Closing since 1.0.0 has been released.
