### ISSUE TITLE
Improve DLC support

### ISSUE THREAD

**Issue by makson96** [sharkwouter/minigalaxy#197]
Basic DLC support is already merged. There are some straight forwards improvements that should be implemented:

- Clearly Mark DLC, which are not owned.
- Add option to update DLCs.
- Investigate if filtering out eBooks, Soundtracks, etc can be improved.

I will work on this one. I think that this issue needs to be addressed before 1.0.0 release. At the moment:

- Clicking to download not owned DLC will result in not very informative error.
- If DLC will require update, user can neither update it, nor uninstall it (without uninstalling whole game), so he/she might stuck with broken DLC.

I want to mark new DLC statuses only by icons:
![error](https://user-images.githubusercontent.com/1833284/99312779-d0336c80-285e-11eb-9102-e1b0c7dbb31c.png) - DLC not owned.
![update_available](https://user-images.githubusercontent.com/1833284/99312816-e5100000-285e-11eb-9002-993ec15e1496.png) - DLC update needed.

So no new translations will be needed.

**Comment by sharkwouter** [comment]
Oh, I did not realize it was displaying DLC which wasn't owned by the user. I think it should not.

**Comment by makson96** [comment]
This one can be closed now.
