### ISSUE TITLE
Do not return error window if start.sh creates new process and set its parent to PID 1

### ISSUE THREAD

**Issue by makson96** [sharkwouter/minigalaxy#203]
If you start Stellaris you get:
![launcher_error](https://user-images.githubusercontent.com/1833284/100098171-f14b1d00-2e5d-11eb-89da-6f550fb75f91.png)
That is because start.sh starts dowser and dowser creates new process for ParadoxLauncher and sets it parents ID to 1.
Then start.sh finishes and miniglaxy thinks that game failed to launch.
I can't offer easy fix as we lost track of game PID in this process. I would go with such a solution:
1. Assume that new process CMD will have game name in it.
2. Run "ps = check_output(["ps", "-ef"]).decode("utf-8")" and search for PIDs higher than minigalxy and with game name in it.
```
makson    8772     1  0 14:01 pts/0    00:00:00 /bin/sh /home/makson/.paradoxlauncher/launcher-v2.2020.15/Paradox Launcher --pdxlGameDir /home/makson/GOG Games/Stellaris/game --gameDir /home/makson/GOG Games/Stellaris/game
```
3. Split this line and use second position as game PID
```
['makson', '8772', '1', '0', '14:01', 'pts/0', '00:00:00', '/bin/sh', '/home/makson/.paradoxlauncher/launcher-v2.2020.15/Paradox', 'Launcher', '--pdxlGameDir', '/home/makson/GOG', 'Games/Stellaris/game', '--gameDir', '/home/makson/GOG', 'Games/Stellaris/game']
```
4. Because start_game() is supposed to return game process, lets track new process and return the trace:
```
process = subprocess.Popen(["strace", "-p", line.split()[1]], stdout=subprocess.PIPE,
                                                   stderr=subprocess.PIPE)
return process
```

If this is acceptable I can proceed with proper solution.
Can I safely assume that "strace" is part of every linux distribution?

**Comment by sharkwouter** [comment]
The best solution for this is probably to check the exit code. This would mean we would miss some error messages, because sometimes games close unexpectedly without a non-zero exit code, but it's better than having the issue we're seeing here.

**Comment by makson96** [comment]
Checking exit code is easier indeed.
start_game() is supposed to return game "process". This "process" is not used anywhere in minigalaxy at the moment. Can we change that behaviour and don't return "process"?
(It would be confusing if function will be sometimes ok and return game process and sometime ok too but doesn't (because process already finished with exit code 0).

**Comment by sharkwouter** [comment]
I guess we can just remove the return statement from the function right now. It doesn't really add anything indeed. This code is a little bit of a mess anyway, to be honest. There shouldn't be that much code for showing an error message in there.

**Comment by sharkwouter** [comment]
Now that I think about it some more, the process should probably be passed onto another function which checks if it crashed and gives an error message if that is the case.

**Comment by makson96** [comment]
I am on it. I will split those large functions in this module to smaller ones, add some some unit tests and move Gtk code to ui/gametile.py (this module should be probably UI independent).

**Comment by makson96** [comment]
Checking exit code is not sufficient. For example Beneath Steel Sky without SCUMMVM:
```
makson@debian-desktop:~/GOG Games/Beneath A Steel Sky$ ./start.sh 
Running Beneath A Steel Sky
Starting ScummVM
/home/makson/GOG Games/Beneath A Steel Sky/scummvm/scummvm_x86_64: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
Done.
makson@debian-desktop:~/GOG Games/Beneath A Steel Sky$ echo $?
0
```

**Comment by makson96** [comment]
Work can be tracked here:
https://github.com/makson96/minigalaxy/tree/fix_launcher_error

**Comment by makson96** [comment]
This one can be closed now after the merge.
