### ISSUE TITLE
Some games will show there is an update even if the latest version is installed

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#207]
An example for this is Bio Menace. I have attached the gameinfo file and server response for that game in this issue.

[server_response_biomenace.txt](https://github.com/sharkwouter/minigalaxy/files/5610410/server_response_biomenace.txt)
[gameinfo_biomenace.txt](https://github.com/sharkwouter/minigalaxy/files/5610407/gameinfo_biomenace.txt)

Other example are:
- Crystal Caves
- Akalabeth: World of Doom
- CAYNE (this one is free)
- Cannon Fodder

I'll update this issue as I find more.

Btw, if you launch minigalaxy with the environment variable MG_DEBUG set. you can see the API requests in the terminal.

**Comment by makson96** [comment]
Yup, game version in gameinfo file is:
2.0.0.2
but API reports:
1.1 (gog-2)

Could you please provide result of:
grep -e gog-2 -r ~/GOG\ Games/Bio\ Menace/
so we could check if API game version is stored somewhere else in game files.

**Comment by sharkwouter** [comment]
Unfortunately, I can't find gog-2 or 1.1 anywhere in the game files with grep, so we have to find a different solution.

I would propose we kill a couple of birds with one stone here and implement the following:

- When a user downloads a game a text file with some json properties is added to the directory the game is in. This could be called something like ``minigalaxy-info.json`` for instance. This would contain the game's name, game id, version, store page url and description as returned by the API when we request the download url.
- When creating tiles, this file is checked first. Meaning we always get all the information we need for a game even in offline mode.
- When updating we use the version in this file and update it.

**Comment by sharkwouter** [comment]
I've added some games to the list.
