### ISSUE TITLE
Checksum failures crash the download manager

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#208]
This leaves the user unable to continue.

**Comment by makson96** [comment]
Could you please provide:
- Python trace back from terminal
- Some easy reproduction steps

**Comment by sharkwouter** [comment]
My bad, I had no time to investigate when I posted this issue initially. I was experiencing this with CAYNE (this game is free, so pretty good for testing) for example:
![Screenshot from 2020-11-29 13-02-09](https://user-images.githubusercontent.com/5042659/100541290-2a5f0500-3243-11eb-8025-c1aa5852b1d7.png)
![Screenshot from 2020-11-29 13-06-07](https://user-images.githubusercontent.com/5042659/100541345-b53fff80-3243-11eb-9707-fe0e89e52740.png)

```
Executing integrity check for /home/wouter/Games/installer/CAYNE/CAYNE
Error, exception encountered: [Errno 13] Permission denied: '/home/wouter/Games/installer/CAYNE/CAYNE'
Exception in thread Thread-161:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wouter/Sources/minigalaxy/minigalaxy/download.py", line 26, in finish
    self.__finish_func()
  File "/home/wouter/Sources/minigalaxy/minigalaxy/ui/gametile.py", line 324, in __update
    install_success = self.__install(update=True)
  File "/home/wouter/Sources/minigalaxy/minigalaxy/ui/gametile.py", line 290, in __install
    install_game(self.game, installer, main_window=self.parent.parent)
  File "/home/wouter/Sources/minigalaxy/minigalaxy/installer.py", line 20, in install_game
    os.remove(installer)
IsADirectoryError: [Errno 21] Is a directory: '/home/wouter/Games/installer/CAYNE/CAYNE'

Failed to install CAYNE: /home/wouter/Games/installer/CAYNE/CAYNE was corrupted. Please download it again.
```

This leaves the download manager broken. It is no longer possible to cancel the update and no other downloads will be started.

This may be 2 issues actually. The exception shown here should be handled better, so the download manager doesn't crash. It seems I downloaded this game with save installers turned on, but it was downloaded with a very old version of Minigalaxy I guess, which is why the file structure is not what was expected.

I've removed the directory now, did a reset and redownloaded. It seems that fixed the issue in this case.
