### ISSUE TITLE
Show store page option doesn't appear anymore

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#209]
Not sure what broke this, but this option is no longer showing up unfortunately. It won't stop the release, but it is a bit of a shame.

**Comment by breversa** [comment]
It still doesn't work after upgrading from 1.0 to 1.0.1 :'(

`System:   Kernel: 5.8.0-34-lowlatency x86_64 bits: 64 Desktop: Cinnamon 4.6.7 Distro: Linux Mint 20 Ulyana`

**Comment by sharkwouter** [comment]
Which games are you seeing this with?

**Comment by breversa** [comment]
All of my installed ones :
![image](https://user-images.githubusercontent.com/2071276/104038902-f8dc4080-51d5-11eb-8076-d084544c7aef.png)

The top-right cogwheel doesn't even appear for non-installed games.

**Comment by breversa** [comment]
Addendum :
**Newly** installed games display the store page option ! :)
