### ISSUE TITLE
Loading the library can take a long time

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#210]
For me when loading my library when starting Minigalaxy takes over 20 seconds. This is because python is bad at multithreading and the window freezes completely until it has checked if there are updates for all the games installed. This should be resolved by making a queue or running it on a different thread in the future. Multiprocess may work here.

**Comment by strycore** [comment]
The concurrent.futures module is really good with that kind of stuff. I use that in Lutris to download icons concurrently. just be careful not to trigger UI changes from anything that runs in an outside thread or process. Get the results to the main thread and do UI updates from there.

**Comment by sharkwouter** [comment]
Thanks for the tip! I'll look into it

**Comment by makson96** [comment]
Do you think we can close this now?

**Comment by sharkwouter** [comment]
Indeed, problem solved
