### ISSUE TITLE
Cannot upgrade because wine-staging

### ISSUE THREAD

**Issue by PrzemekSkw** [sharkwouter/minigalaxy#216]
Hi, I try to upgrade to 1.0 version but it ask to install wine and uninstall my wine-staging. When I uncheck wine from deps to install I have version 0.9.4. My app manager Bauh show me I have installed ver. 1.0.
I don't want to have regular wine. I want wine-staging.

![Zrzut ekranu z 2020-11-30 11-42-19](https://user-images.githubusercontent.com/25219988/100600250-550f9300-3301-11eb-82f8-9792bed9070c.png)
![Zrzut ekranu z 2020-11-30 11-42-47](https://user-images.githubusercontent.com/25219988/100600257-580a8380-3301-11eb-87bb-1b2c7264ba4f.png)

Regards,
Przemek

**Comment by Newbytee** [comment]
Probably a duplicate of https://github.com/sharkwouter/minigalaxy/issues/217.

**Comment by makson96** [comment]
Is this still the case for Minigalaxy 1.0.2?

**Comment by sharkwouter** [comment]
Should work with the new version, wine is only a suggested dependency now.

**Comment by PrzemekSkw** [comment]
Hi, sorry for late response I see now it was upgraded last time to 1.0.2 and now it's OK.
Regards.

**Comment by sharkwouter** [comment]
Great, thanks for reporting back
