### ISSUE TITLE
1.0.0 shows as 0.9.4 in About

### ISSUE THREAD

**Issue by tim77** [sharkwouter/minigalaxy#217]
Minor issue but worth to mention i hope. Downstream report https://bodhi.fedoraproject.org/updates/FEDORA-2020-4e51555cae#comment-1753743

**Comment by sharkwouter** [comment]
Yeah, this one slipped through the cracks in the release process twice now. I need to automate this.

**Comment by sharkwouter** [comment]
This should be fixed in 1.0.1
