### ISSUE TITLE
Stonekeep detected as windows game but it's a DOS game

### ISSUE THREAD

**Issue by baraclese** [sharkwouter/minigalaxy#219]
In the Stonekeep folder there is a unins000.exe file so that it gets detected as windows program.

**Comment by makson96** [comment]
Could you please provide whole game directory content?
"ls" command result from game directory should be sufficient.

**Comment by baraclese** [comment]
CD/
CONFIG
DATA/
DOS4GW.EXE
DOSBOX/
'DOSBox Configuration.lnk'
dosboxStonekeep.conf
dosboxStonekeep_settings.conf
dosboxStonekeep_single.conf
EULA.txt
GameuxInstallHelper.dll
goggame-1207658671.dll
goggame-1207658671.hashdb
goggame-1207658671.ico
goggame-1207658671.info
gog.ico
'Launch Settings.lnk'
'Launch Stonekeep.lnk'
manual.pdf
PATCH/
prefix/
README.TXT
SETUP.EXE
SK.EXE
Support.ico
thumbnail.jpg
unins000.dat
unins000.exe
unins000.msg
webcache.zip

**Comment by makson96** [comment]
Thanks for the info. Pull request with the fix is waiting for review now.

**Comment by sharkwouter** [comment]
Since Stonekeep is only provided for Windows on GOG, I'm going the close this in favor of #64.
