### ISSUE TITLE
Preferences - Stay Logged In

### ISSUE THREAD

**Issue by SwampRabbit** [sharkwouter/minigalaxy#22]
I would like to suggest an addition to Preferences, with a selection option to Stay Logged In.

Currently the default is to keep users logged in unless they select Logout from the menu.

This would allow users choose if they want have the client logout after closing or to stay logged in.

Thank you for your consideration.

**Comment by sharkwouter** [comment]
That's a pretty good idea actually. It won't be high priority for now, though, but I'll keep it open and work on it later

**Comment by SwampRabbit** [comment]
Thank you, no rush at all.  Keep up the great work, it is an amazing application.

**Comment by sharkwouter** [comment]
This has been implemented in #37, thanks @Odelpasso! The feature will be available in the next release.

**Comment by SwampRabbit** [comment]
@sharkwouter and @Odelpasso thank you for implementing this so quickly.  Keep up the great work, it is really appreciated!
