### ISSUE TITLE
No games in the view

### ISSUE THREAD

**Issue by Gildraen** [sharkwouter/minigalaxy#223]
Hi, i just installed the 1.0.0, but i have ONLY CyberPunk 2077.
And so i open the application and there is no game to install or other. 
Are games added manually on the application ? Or what do i have to do to show the game ?  
Thanks in advance !

**Comment by sharkwouter** [comment]
Cyberpunk 2077 is not available for Linux and by default Minigalaxy will only show Linux games in your library. You can enable showing Windows games in the settings.
