### ISSUE TITLE
Move to GTK 4.0

### ISSUE THREAD

**Issue by Newbytee** [sharkwouter/minigalaxy#227]
GTK 4.0 is finally out after years of waiting, so I'm creating this issue to discuss the possibility of and presumably to track the progress of porting Minigalaxy to GTK 4.0.

**Comment by stephanlachnit** [comment]
If you do this keep in mind that Ubuntu 20.04 users won't be able to use this.

**Comment by sharkwouter** [comment]
This won't happen for a while. We need distributions to start shipping GTK 4.0 and PyGObject to support it before we can consider using it.

**Comment by sharkwouter** [comment]
For now this issue is not really relevant yet and totally out of our control. Because of this I'm closing it for now. Thanks for the report, though. I'll keep an eye what distributions will do with gtk 4.
