### ISSUE TITLE
[Feature Request] Support Game List from other stores

### ISSUE THREAD

**Issue by Protektor-Desura** [sharkwouter/minigalaxy#230]
It would be nice if you could use the same Python plugins that the GOG Galaxy uses to list and play/launch all the games from other stores.

**Comment by sharkwouter** [comment]
Thanks for the request. I've thought about it some more, but ultimately I still think it is a good thing that Minigalaxy only supports GOG making it very focussed. There are multiple other options available if you want a client which supports more stores like Gamehub and Lutris.
