### ISSUE TITLE
MiniGalaxy crashes if ~/GoG Games does not exist

### ISSUE THREAD

**Issue by Odelpasso** [sharkwouter/minigalaxy#24]
Hello,

If ~/GoG Games does not exist and if i launch for the 1st time MiniGalaxy, it crashes with these errors : 

> Traceback (most recent call last):
>   File "/usr/bin/minigalaxy", line 66, in <module>
>     main()
>   File "/usr/bin/minigalaxy", line 60, in main
>     window = Window(APPLICATION_NAME)
>   File "/usr/lib64/python3.6/site-packages/minigalaxy/window/window.py", line 48, in __init__
>     self.sync_library()
>   File "/usr/lib64/python3.6/site-packages/minigalaxy/window/window.py", line 55, in sync_library
>     installed_games = self.__get_installed_games()
>   File "/usr/lib64/python3.6/site-packages/minigalaxy/window/window.py", line 187, in __get_installed_games
>     directories = os.listdir(self.config.get("install_dir"))
> FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/odelpasso/GOG Games'

I need to create manually the folder to avoid the crash.

**Comment by sharkwouter** [comment]
Oh I see, thanks for reporting, I would probably not have found this issue. It should be resolved now, but you may have to start minigalaxy with the ``--reset`` option once.
