### ISSUE TITLE
Installation of game failed due to missing libGLU.so.1

### ISSUE THREAD

**Issue by DHLF** [sharkwouter/minigalaxy#250]
Distro:Debian GNU/Linux 10 (buster)
Kernel:5.9.0-0.bpo.2-amd64
RAM:32 GB
GPU Driver:4.5 Mesa 18.3.6
GPU:AMD VEGA20
CPU:AMD Ryzen Threadripper 1900X 8-Core

Error message disappears and installation works after manual installation of missing package:
apt-get install libglu1-mesa:i386

I had already installed steam before(including suggested dependencies for steam like mesa, vulkan,..).

Perhaps steam uses own libraries and therefore those missing libGLU was no problem.

What would have been suggested packages needed to play gog games on linux?

**Comment by sharkwouter** [comment]
Which game was this? I don't think all games require this.

**Comment by sharkwouter** [comment]
I'm going to close this one for now. Minigalaxy itself does not require this library to be able to work, so I don't think it's up to us to solve it. Thank you for reporting, anyway, though. All contributions are appreciated.
