### ISSUE TITLE
DLC icon missing

### ISSUE THREAD

**Issue by stephanlachnit** [sharkwouter/minigalaxy#251]
The icon on the DLC button is missing. I haven't tried to search for it in the code, but it seems like you use an icon which is not in the default icon set. If you give the code line of where you create the button in Gtk I can take a look as well.

![Screenshot from 2021-01-08 15-25-02](https://user-images.githubusercontent.com/36662302/104026378-1d302100-51c6-11eb-9155-a1805f48ccd9.png)

**Comment by sharkwouter** [comment]
Oh that could be, the code for that can be found here:

https://github.com/sharkwouter/minigalaxy/blob/1dcc82b4f9e2e00a5d58bc4116b5348b75e3df32/minigalaxy/ui/gametile.py#L367-L397

The icons used are gtk-cdrom, gtk-okay and gtk-goto-bottom. I'm not sure which one is not in the standard set.

**Comment by stephanlachnit** [comment]
Hm, I think the issue is that the `gtk-xxx` icons have been replaced with the Adwaita icon theme.

**Comment by makson96** [comment]
Hmm, can we perform some check if gtk-xxx icon is available and if not use adwaita-xxx instead?

**Comment by sharkwouter** [comment]
It seems in Ubuntu these icons are in the humanity-icon-theme package, but Debian doesn't have these.

**Comment by sharkwouter** [comment]
It seems the gnome-human-icon-theme has some of the icons we use, but not all of them it seems.

**Comment by stephanlachnit** [comment]
Any reason you don't use icons from Adwaita? That's the default Gtk icon theme these days.

Some quick replacing I found:
`gtk-cdom` - `media-optical-symbolic`
`gtk-ok` - `emblem-ok-symbolic`
`gtk-goto-bottom` - `document-save-symbolic`

**Comment by makson96** [comment]
I can replace them with Adwaita if @sharkwouter is ok with this.
I would rather use accordingly:
media-optical
emblem-default
go-bottom
Minigalaxy is colourful no need to use "symbolic".
Is Adwaita available in all major distributions?

**Comment by stephanlachnit** [comment]
Adwaita is in every distro: https://repology.org/project/adwaita-icon-theme/versions

Regarding symbolic: I don't think Adwaita has these icons in non-symbolic. These days UI icons are always symbolic, so that shell themes can work properly.

**Comment by makson96** [comment]
I see non-symbolic (all icons I mentioned) here:
https://packages.debian.org/buster/all/adwaita-icon-theme/filelist

**Comment by sharkwouter** [comment]
Using Adwaita sounds like the best option to solve this. There are probably more distributions which have issues with the current icons.

**Comment by stephanlachnit** [comment]
> I see non-symbolic (all icons I mentioned) here:
> https://packages.debian.org/buster/all/adwaita-icon-theme/filelist

My bad, seems like some of them exist, but in the latest version (3.38) they are marked as legacy, so I wouldn't use them.

**Comment by sharkwouter** [comment]
I've merged the icon change. Does the cancel icon work which is shown when downloading? That is also an old one

Do you need me to do a mini release or a tag to be able to package this btw?

**Comment by stephanlachnit** [comment]
Minigalaxy 1.0.1 is already in NEW, a queue where every new package needs to be reviewed manually (after it passed that isn't required for updates).

This process can take from a few days to sometimes weeks depending on the workload of the people. I hope this gets reviewd before the freeze in February. The review is more about copyright and packaging practices then about potential bugs so this isn't a high prio issue for now.

If you feel like doing a release, go ahead, but you can also wait to accumulate more changes if you want.
