### ISSUE TITLE
Game Installs And Loads Initially But Closing And Re-Loading The Game Does Not Work

### ISSUE THREAD

**Issue by intelligentgaming** [sharkwouter/minigalaxy#253]
Basically I can download and install games from my GOG account, initially they work, but if I exit the game and try to run them again, they do not load. 

For example, Daggerfall uses DosBox, which works initially but any subsequent load, loads up DosBox and not the game.

Fallout 3 initially loads, but any subsequent running off the game loads open up the window with Play, Options, Data Files, Techsupport and Exit, as normal but clicking Play brings up the below message. 

![image](https://user-images.githubusercontent.com/67860954/104071951-12937d00-5202-11eb-9c26-e7c861401cd8.png)

The games are installed at /home/ryan/GOG Games.

I have a shortcut on my desktop, for both games but executing them brings up a message that the file reference is not found. 

Kubuntu 20.10 on this machine, but the same happens on my laptop running Garuda Linux.

**Comment by makson96** [comment]
From our launcher perspective there doesn't seems to be any difference between first and second run. Could you provide the answer to those questions:
1. Are you using Minigalaxy 1.0.1?
2. Are game files in /home/ryan/GOG Games/Fallout 3 appear to be ok?
3. If you move /home/ryan/GOG Games/Fallout 3/prefix to /home/ryan/GOG Games/Fallout 3/prefix_back will the game start normally again?

**Comment by intelligentgaming** [comment]
1 - Yes
2 - Yes, as far as I can see.
3 - No (See below).

![image](https://user-images.githubusercontent.com/67860954/104089309-d72a9a00-5265-11eb-834b-75619c29779c.png)

**Comment by makson96** [comment]
Well, personally I don't know what's going on and I don't have those games to check it by myself. Maybe someone else have better idea.
