### ISSUE TITLE
DLC update is never shown

### ISSUE THREAD

**Issue by makson96** [sharkwouter/minigalaxy#261]
I discovered this issue while checking icons pull request #258 
It seems that if DLC is installed, it is never checked for update.
I already proposed fix in mentioned pull request, but if you prefer, I can create separate pull request with the fix.

**Comment by sharkwouter** [comment]
It might be better to have a separate pull request for it, preferably with a test for it.

**Comment by sharkwouter** [comment]
This should be fixed now
