### ISSUE TITLE
Couldn't connect to GOG servers

### ISSUE THREAD

**Issue by voltumna** [sharkwouter/minigalaxy#271]
Hi all, 
I downloaded and installed minigalaxy app, awesome idea! 
I am having an issue: when I started the app the first time, it showed me the login prompt for GOG, and that was fine, but then right away after logging in I get this message:

"Couldn't connect to GOG servers"

any suggestions?

Thanks

**Comment by sharkwouter** [comment]
Thanks for the report, I've not seen this before. Which version is this? Can you access the GOG website? If you launch minigalaxy from the terminal, do you see any output?

**Comment by voltumna** [comment]
Hi, 
thank you for the fast feedback. 
Via the browser, I can totally connect, i can log in and everything you can do on the website,

I have tried via the commandline, but there is no output at all, 

I have version 1.0.2
here is a screenshot with the output of the command line
![image](https://user-images.githubusercontent.com/1274922/104614020-20288700-5688-11eb-9439-c4f40a31670e.png)

**Comment by sharkwouter** [comment]
Now that is strange. Maybe running Minigalaxy from the terminal like so will give some more information: ``MG_DEBUG=1 minigalaxy``

**Comment by voltumna** [comment]
Thank you, i have done it and it looks like the took does get a response but it is not recognising it:
![image](https://user-images.githubusercontent.com/1274922/104620912-cf1c9100-568f-11eb-8a71-67f634a35040.png)

**Comment by makson96** [comment]
OK. Lets debug this a little.
This error is provided by:
minigalaxy/ui/library.py
from "__add_games_from_api()" function.
It is becausethere were no games retrived by minigalaxy/api.py api.get_library().
Now I think this is because active_token is false for some reason.
I believe that something went wrong "response_params = response.json()" either in __refresh_token() or in __get_token()

@voltumna could you please modify minigalaxy/api.py file from line 35 to 72 so it would look like that (add additional prints):
```
    def __refresh_token(self, refresh_token: str) -> str:
        request_url = "https://auth.gog.com/token"
        params = {
            'client_id': self.client_id,
            'client_secret': self.client_secret,
            'grant_type': 'refresh_token',
            'refresh_token': refresh_token,
        }
        response = SESSION.get(request_url, params=params)

        response_params = response.json()
        print("refresh token")
        print(response_params)
        if "access_token" in response_params and "expires_in" in response_params and "refresh_token" in response_params:
            self.active_token = response_params["access_token"]
            expires_in = response_params["expires_in"]
            self.active_token_expiration_time = time.time() + int(expires_in)
            response_token = response_params["refresh_token"]
        else:
            response_token = ""
        return response_token

    # Get a token based on the code returned by the login screen
    def __get_token(self, login_code: str) -> str:
        request_url = "https://auth.gog.com/token"
        params = {
            'client_id': self.client_id,
            'client_secret': self.client_secret,
            'grant_type': 'authorization_code',
            'code': login_code,
            'redirect_uri': self.redirect_uri,
        }
        response = SESSION.get(request_url, params=params)

        response_params = response.json()
        print("get token")
        print(response_params)
        self.active_token = response_params['access_token']
        expires_in = response_params["expires_in"]
        self.active_token_expiration_time = time.time() + int(expires_in)

        return response_params['refresh_token']
```
And show us what is printed on terminal?

**Comment by voltumna** [comment]
here is my output, I still get that error:

` mau  ~  sudo vi /usr/lib/python3/dist-packages/minigalaxy/api.py
 mau  ~  MG_DEBUG=1 minigalaxy
refresh token
{'access_token': '64Ig5ariMj-LfCNk5N8x9lWWDSWZTpAAA-HzkC6nNBu3mNK2ilCuQxM8yWfSELFDzdZdG45G-jE9BXpYSt7JbX8ROTTtQCTbsLqmWgZXPMQhw7R10PXFOMUzKt0QWCOozfMTy5MErdpp5zD2L35gvE6dIEt0ypxAmE4OP1LGjsw', 'expires_in': 3600, 'token_type': 'bearer', 'scope': '', 'session_id': '6917613940145835703', 'refresh_token': 'FsNp_aCr8mIT8jWqgizoBQ6A5Tg7PBNj6yE5f1_tIPyPG8O4NajIGJLi3c9m0RrN', 'user_id': '53934425578930372'}
Request: https://embed.gog.com/user/data/games
Return code: 200
Response body: {"owned":[1423049311,1548764757,1182612231,1421626738,1601676413,1998727699,2093619782]}

Request: https://embed.gog.com/account/getFilteredProducts
Return code: 200
Response body: {"sortBy":null,"page":1,"totalProducts":2,"totalPages":1,"productsPerPage":100,"contentSystemCompatibility":null,"moviesCount":0,"tags":[{"id":"553452313","name":"COMPLETED","productCount":"0"},{"id":"553452310","name":"NEXT TO PLAY","productCount":"0"},{"id":"553452307","name":"BACKLOG","productCount":"0"},{"id":"553452304","name":"FAVORITE","productCount":"0"}],"products":[{"isGalaxyCompatible":true,"tags":[],"id":1423049311,"availability":{"isAvailable":false,"isAvailableInAccount":true},"title":"Cyberpunk 2077","image":"\/\/images-1.gog-statics.com\/5a51d9484a3985b1f6e37eddc1853cb6d84bece22e2a5d80dfdbf30d3b0e8444","url":"\/game\/cyberpunk_2077","worksOn":{"Windows":true,"Mac":false,"Linux":false},"category":"","rating":0,"isComingSoon":false,"isMovie":false,"isGame":true,"slug":"cyberpunk_2077_game","updates":0,"isNew":false,"dlcCount":0,"releaseDate":{"date":"-0001-11-30 00:00:00.000000","timezone_type":3,"timezone":"Europe\/Nicosia"},"isBaseProductMissing":false,"isHidingDisabled":false,"isInDevelopment":false,"isHidden":false},{"isGalaxyCompatible":true,"tags":[],"id":1548764757,"availability":{"isAvailable":false,"isAvailableInAccount":true},"title":"Cyberpunk 2077 Digital Goodies","image":"\/\/images-1.gog-statics.com\/0a12c6d08925b4e567dd56bd3cd70b3a0667ea484539bada5b8698f4add72dcf","url":"","worksOn":{"Windows":true,"Mac":false,"Linux":false},"category":"","rating":0,"isComingSoon":false,"isMovie":false,"isGame":true,"slug":"cyberpunk_2077_digital_goodies","updates":0,"isNew":false,"dlcCount":0,"releaseDate":{"date":"-0001-11-30 00:00:00.000000","timezone_type":3,"timezone":"Europe\/Nicosia"},"isBaseProductMissing":false,"isHidingDisabled":false,"isInDevelopment":false,"isHidden":false}],"updatedProductsCount":0,"hiddenUpdatedProductsCount":0,"appliedFilters":{"tags":null},"hasHiddenProducts":true}
`

I hope this helps

**Comment by makson96** [comment]
Sorry I think I missed.
Do only own Cyberpunk Game on GoG?
If so this game doesn't have Linux support and that is why Miniglaxy think that your library is initially empty.
Could you claim some free Linux game and tell us if this issue is gone. For example:
https://www.gog.com/game/beneath_a_steel_sky

**Comment by voltumna** [comment]
Indeed, I 'only' had Cyberpunk and hoped that like in Steam, you can force-play it on a linux platform, oh well.
Anyways, that is cool, adding the game you suggested worked! now it connected and I can see the game in the list!

Wonderful, so I guess that this is something to take into account: that if you do not have a game list for linux, it will give that error,

might need to check it out ;)

Thank you again!

**Comment by makson96** [comment]
Yep. I think we should keep this issue open. We should probably handle this corner case differently.

**Comment by sharkwouter** [comment]
It is odd that Minigalaxy will think there is no connection when there are no games. That is a bug

**Comment by voltumna** [comment]
Indeed, I guess it is a default error because there is a comparison that expects the response to have 'list of games' to be >0 and not >=0 .
and that is incorporated in the connection check

**Comment by conqp** [comment]
I encountered the same issue.
I just wanted to download a Windows game.
Windows games are disabled by default, so minigalaxy's game list is empty and it thinks it's offline.
After removing the game list check and statically setting `self.online = True`, I was able to run it, enable the listing of Windows games and download the respective game. Sheesh.
```diff
--- /home/rne/library.py	2021-04-08 20:00:34.622438095 +0200
+++ ui/library.py	2021-04-08 19:55:01.013065041 +0200
@@ -145,12 +145,13 @@
 
     def __add_games_from_api(self):
         retrieved_games = self.api.get_library()
-        if retrieved_games:
-            self.offline = False
-        else:
-            retrieved_games = []
-            self.offline = True
-            GLib.idle_add(self.parent.show_error, _("Failed to retrieve library"), _("Couldn't connect to GOG servers"))
+        #if retrieved_games:
+        #    self.offline = False
+        self.offline = True
+        #else:
+        #    retrieved_games = []
+        #    self.offline = True
+        #    GLib.idle_add(self.parent.show_error, _("Failed to retrieve library"), _("Couldn't connect to GOG servers"))
         for game in retrieved_games:
             if game not in self.games:
                 self.games.append(game)
```

**Comment by sharkwouter** [comment]
This should be fixed in the master branch now. If you test it, please let me know the result.
