### ISSUE TITLE
Add option to hide games

### ISSUE THREAD

**Issue by makson96** [sharkwouter/minigalaxy#273]
As on Discord request:
"
Jero09.01.2021
Hi, just a feature idea since I would really like to see it. I would like to hide some games from the list. I did claim some free games on gog which I don't want to play or to see, so I don't want to see them in my list
"
There should be obviously option to unhide games. Maybe in hamburger menu on top panel?

**Comment by sharkwouter** [comment]
We can add it to the properties menu and add "show hidden games" to the hamburger menu
