### ISSUE TITLE
Windows games endless update circle

### ISSUE THREAD

**Issue by Angell1993** [sharkwouter/minigalaxy#278]
After updating Minigalaxy, I noticed something quite interesting, it kept telling me to update any game that uses wine, even though the games are installed and working.. And it don't use custom game folder path during installation anymore..

I can provide image links if needed..

**Comment by makson96** [comment]
Thanks for the report. In game directory there should be minigalaxy-info.json file. Could you paste here its content?

**Comment by Angell1993** [comment]
the file minigalaxy-info.json, that you are asking about doesn't seem to exist.. So I can't provide a file I can't find..
I've checked the game folder, the .cache folder unless there is another place I don't know about then it doesn't exist on my system..

**Comment by makson96** [comment]
Thanks for the info. It is very helpful.

**Comment by sharkwouter** [comment]
Interesting, which version of Minigalaxy are you using?

**Comment by Angell1993** [comment]
The latest version on Arch Linux Aur, so properly the latest version of the app at this time.. v1.0.2..

**Comment by sharkwouter** [comment]
Okay, thanks!

**Comment by Angell1993** [comment]
I'm still having this issue, so had there been any progress on it??
Even a temporary solution by an option, by typing in the version of the game, so it wouldn't ask to update when the game is already the latest version.. As I can tell only Windows games are affected..

**Comment by sharkwouter** [comment]
There was no progress on this yet. I just haven't gotten to it. I personally don't play many Windows games on GOG, so it's not really at the top of my list at the moment. Sorry about that. Help is welcome on this one.

**Comment by makson96** [comment]
@Angell1993 can you check if the problem persists with current master branch? We changed files location containing version info. Maybe this will fix this issue.

**Comment by Angell1993** [comment]
@makson96 Well, I managed to fix the issue myself, by assigning the correct version number, to a few games.. By using the json file in the game folder..
And the games themselves did correct themselves after reinstall..

I manually use the lgogdownloader for games like Cyperpunk 2077 because then I can use Proton to launch it, seeing it will only work in Proton.. I like the custom start.sh I can use in the game folder when installed in this way..

**Comment by makson96** [comment]
> And the games themselves did correct themselves after reinstall..

So can we consider this issue to be fixed?

**Comment by Angell1993** [comment]
I'd say so..

**Comment by sharkwouter** [comment]
Thanks for the update guys!
