### ISSUE TITLE
Cancel queued download leads to error due to FileNotFoundError

### ISSUE THREAD

**Issue by SvdB-nonp** [sharkwouter/minigalaxy#283]
The on_button_cancel() method (line 129 of gametile.py) can result in a filenotfound error as it tries to remove the downloaded files (~/.cache/minigalaxy/download/<GameName>), which are not there for a queued download.

Sounds like an easy fix to catch the FileNotFoundError and skip removal of the download folder.

**Comment by sharkwouter** [comment]
Thanks for the report. I'll take a look at it.

**Comment by sharkwouter** [comment]
Should be fixed in master now
