### ISSUE TITLE
could not be unzipped - error after installation succeeded

### ISSUE THREAD

**Issue by tastytea** [sharkwouter/minigalaxy#287]
After I successfully installed “RollerCoaster Tycoon 2 Triple Thrill Pack”, I got the error message: 

```
/tmp/tastytea/.cache/minigalaxy/download/RollerCoaster Tycoon 2 Triple Thrill Pack/setup_rollercoaster_tycoon_2_triple_thrill_pack_2.01.043_(17987).exe could not be unzipped.
```

But the game starts fine.

**Comment by sharkwouter** [comment]
Thanks for the report. This is strange, it shouldn't try to do that. I'll see if I find time to look into it on the weekend.

**Comment by sharkwouter** [comment]
Unfortunately I haven't gotten to this yet. Give me some time, I'm trying to also solve another problem in another project at the moment, sorry about that.

**Comment by sharkwouter** [comment]
At this point I don't know if this issue still exists.

**Comment by tastytea** [comment]
I uninstalled the game, reinstalled it and started it. I don't get the message anymore.

**Comment by sharkwouter** [comment]
Okay, that is interesting. Thanks for testing!
