### ISSUE TITLE
Manuel install of Minigalaxy Error

### ISSUE THREAD

**Issue by Angell1993** [sharkwouter/minigalaxy#295]
Everything looks to install fine, but can't launch after manuel install with python.. Hope this makes any sense to you, seeing everything are located in the right places..

Traceback (most recent call last):
  File "/usr/bin/minigalaxy", line 4, in <module>
    __import__('pkg_resources').run_script('minigalaxy==1.0.2', 'minigalaxy')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/angel/.local/lib/python3.9/site-packages/minigalaxy-1.0.2-py3.9.egg/EGG-INFO/scripts/minigalaxy", line 66, in <module>
    main()
  File "/home/angel/.local/lib/python3.9/site-packages/minigalaxy-1.0.2-py3.9.egg/EGG-INFO/scripts/minigalaxy", line 57, in main
    from minigalaxy.ui import Window
  File "/home/angel/.local/lib/python3.9/site-packages/minigalaxy-1.0.2-py3.9.egg/minigalaxy/ui/__init__.py", line 2, in <module>
    from minigalaxy.ui.window import Window
  File "/home/angel/.local/lib/python3.9/site-packages/minigalaxy-1.0.2-py3.9.egg/minigalaxy/ui/window.py", line 6, in <module>
    from minigalaxy.ui.login import Login
  File "/home/angel/.local/lib/python3.9/site-packages/minigalaxy-1.0.2-py3.9.egg/minigalaxy/ui/login.py", line 13, in <module>
    class Login(Gtk.Dialog):
  File "/usr/lib/python3.9/site-packages/gi/_gtktemplate.py", line 226, in __call__
    bytes_ = GLib.Bytes.new(file_.load_contents()[1])
gi.repository.GLib.Error: g-io-error-quark: Error opening file /usr/share/minigalaxy/ui/login.ui: No such file or directory (1)

**Comment by Angell1993** [comment]
[Terminal manuel install]

python setup.py install --user                                   [1]
running install
running bdist_egg
running egg_info
writing minigalaxy.egg-info/PKG-INFO
writing dependency_links to minigalaxy.egg-info/dependency_links.txt
writing requirements to minigalaxy.egg-info/requires.txt
writing top-level names to minigalaxy.egg-info/top_level.txt
writing manifest file 'minigalaxy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/__init__.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/download.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/constants.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/paths.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/version.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/installer.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/download_manager.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/api.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/config.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/launcher.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/game.py -> build/bdist.linux-x86_64/egg/minigalaxy
copying build/lib/minigalaxy/css.py -> build/bdist.linux-x86_64/egg/minigalaxy
creating build/bdist.linux-x86_64/egg/minigalaxy/ui
copying build/lib/minigalaxy/ui/__init__.py -> build/bdist.linux-x86_64/egg/minigalaxy/ui
copying build/lib/minigalaxy/ui/preferences.py -> build/bdist.linux-x86_64/egg/minigalaxy/ui
copying build/lib/minigalaxy/ui/gametile.py -> build/bdist.linux-x86_64/egg/minigalaxy/ui
copying build/lib/minigalaxy/ui/login.py -> build/bdist.linux-x86_64/egg/minigalaxy/ui
copying build/lib/minigalaxy/ui/window.py -> build/bdist.linux-x86_64/egg/minigalaxy/ui
copying build/lib/minigalaxy/ui/about.py -> build/bdist.linux-x86_64/egg/minigalaxy/ui
copying build/lib/minigalaxy/ui/properties.py -> build/bdist.linux-x86_64/egg/minigalaxy/ui
copying build/lib/minigalaxy/ui/library.py -> build/bdist.linux-x86_64/egg/minigalaxy/ui
copying build/lib/minigalaxy/translation.py -> build/bdist.linux-x86_64/egg/minigalaxy
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/download.py to download.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/constants.py to constants.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/paths.py to paths.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/version.py to version.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/installer.py to installer.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/download_manager.py to download_manager.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/api.py to api.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/config.py to config.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/launcher.py to launcher.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/game.py to game.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/css.py to css.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/ui/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/ui/preferences.py to preferences.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/ui/gametile.py to gametile.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/ui/login.py to login.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/ui/window.py to window.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/ui/about.py to about.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/ui/properties.py to properties.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/ui/library.py to library.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/minigalaxy/translation.py to translation.cpython-39.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/share
creating build/bdist.linux-x86_64/egg/share/applications
copying data/io.github.sharkwouter.Minigalaxy.desktop -> build/bdist.linux-x86_64/egg/share/applications
creating build/bdist.linux-x86_64/egg/share/icons
creating build/bdist.linux-x86_64/egg/share/icons/hicolor
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/128x128
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/128x128/apps
copying data/icons/128x128/io.github.sharkwouter.Minigalaxy.png -> build/bdist.linux-x86_64/egg/share/icons/hicolor/128x128/apps
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/192x192
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/192x192/apps
copying data/icons/192x192/io.github.sharkwouter.Minigalaxy.png -> build/bdist.linux-x86_64/egg/share/icons/hicolor/192x192/apps
creating build/bdist.linux-x86_64/egg/share/minigalaxy
creating build/bdist.linux-x86_64/egg/share/minigalaxy/ui
copying data/ui/about.ui -> build/bdist.linux-x86_64/egg/share/minigalaxy/ui
copying data/ui/login.ui -> build/bdist.linux-x86_64/egg/share/minigalaxy/ui
copying data/ui/library.ui -> build/bdist.linux-x86_64/egg/share/minigalaxy/ui
copying data/ui/application.ui -> build/bdist.linux-x86_64/egg/share/minigalaxy/ui
copying data/ui/properties.ui -> build/bdist.linux-x86_64/egg/share/minigalaxy/ui
copying data/ui/gametile.ui -> build/bdist.linux-x86_64/egg/share/minigalaxy/ui
copying data/ui/preferences.ui -> build/bdist.linux-x86_64/egg/share/minigalaxy/ui
creating build/bdist.linux-x86_64/egg/share/minigalaxy/images
copying data/images/winehq_logo_glass.png -> build/bdist.linux-x86_64/egg/share/minigalaxy/images
creating build/bdist.linux-x86_64/egg/share/metainfo
copying data/io.github.sharkwouter.Minigalaxy.metainfo.xml -> build/bdist.linux-x86_64/egg/share/metainfo
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/de
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/de/LC_MESSAGES
copying data/mo/de/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/de/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/es
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/es/LC_MESSAGES
copying data/mo/es/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/es/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/fr
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/fr/LC_MESSAGES
copying data/mo/fr/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/fr/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/nb_NO
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/nb_NO/LC_MESSAGES
copying data/mo/nb_NO/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/nb_NO/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/nl
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/nl/LC_MESSAGES
copying data/mo/nl/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/nl/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/nn_NO
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/nn_NO/LC_MESSAGES
copying data/mo/nn_NO/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/nn_NO/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/pl
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/pl/LC_MESSAGES
copying data/mo/pl/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/pl/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/pt_BR
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/pt_BR/LC_MESSAGES
copying data/mo/pt_BR/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/pt_BR/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/ru_RU
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/ru_RU/LC_MESSAGES
copying data/mo/ru_RU/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/ru_RU/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/tr
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/tr/LC_MESSAGES
copying data/mo/tr/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/tr/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/zh_CN
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/zh_CN/LC_MESSAGES
copying data/mo/zh_CN/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/zh_CN/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/zh_TW
creating build/bdist.linux-x86_64/egg/share/minigalaxy/translations/zh_TW/LC_MESSAGES
copying data/mo/zh_TW/LC_MESSAGES/minigalaxy.mo -> build/bdist.linux-x86_64/egg/share/minigalaxy/translations/zh_TW/LC_MESSAGES/
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.9/minigalaxy -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/minigalaxy to 755
copying minigalaxy.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying minigalaxy.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying minigalaxy.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying minigalaxy.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying minigalaxy.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/minigalaxy-1.0.2-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing minigalaxy-1.0.2-py3.9.egg
removing '/home/angel/.local/lib/python3.9/site-packages/minigalaxy-1.0.2-py3.9.egg' (and everything under it)
Copying minigalaxy-1.0.2-py3.9.egg to /home/angel/.local/lib/python3.9/site-packages
minigalaxy 1.0.2 is already the active version in easy-install.pth
Installing minigalaxy script to /home/angel/.local/bin

Installed /home/angel/.local/lib/python3.9/site-packages/minigalaxy-1.0.2-py3.9.egg
Processing dependencies for minigalaxy==1.0.2
Searching for requests==2.25.1
Best match: requests 2.25.1
Processing requests-2.25.1-py3.9.egg
requests 2.25.1 is already the active version in easy-install.pth

Using /usr/lib/python3.9/site-packages/requests-2.25.1-py3.9.egg
Searching for PyGObject==3.38.0
Best match: PyGObject 3.38.0
Adding PyGObject 3.38.0 to easy-install.pth file

Using /usr/lib/python3.9/site-packages
Searching for urllib3==1.26.3
Best match: urllib3 1.26.3
Adding urllib3 1.26.3 to easy-install.pth file

Using /usr/lib/python3.9/site-packages
Searching for idna==2.10
Best match: idna 2.10
Adding idna 2.10 to easy-install.pth file

Using /usr/lib/python3.9/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /home/angel/.local/bin

Using /usr/lib/python3.9/site-packages
Searching for certifi==2020.6.20
Best match: certifi 2020.6.20
Adding certifi 2020.6.20 to easy-install.pth file

Using /usr/lib/python3.9/site-packages
Finished processing dependencies for minigalaxy==1.0.2

**Comment by sharkwouter** [comment]
You'll need to put the minigalaxy binary in build/bdist.linux-x86_64/egg/bin/ in order for this to work. It looks for data in ../usr/share/minigalaxy from its current location.

**Comment by Angell1993** [comment]
Well, after a rather extensive clean up of minigalaxy from the manuel install, I couldn't get the Normal AUR package to work, but I got the Git version from AUR to work.. So I'll just stick to AUR git version seeing that one actually works after puthon setup literally messed with the system..

All I wanted was to check if anything new had been added, before the actual release..

**Comment by sharkwouter** [comment]
What went wrong with the AUR package? I maintain and use that one myself.

**Comment by sharkwouter** [comment]
Ah okay, for that we have some instructions here: https://github.com/sharkwouter/minigalaxy/wiki/Developer-information#setting-up-a-development-environment

You don't actually need to install to just test the latest git version.

**Comment by Angell1993** [comment]
The normal AUR package, just didn't work after the my messy try at using the manuel python install, but after I manually cleaned up the system, I managed to get the AUR Git package to work.. Not sure what the difference is between the two AUR packages..

**Comment by sharkwouter** [comment]
The git package pulls in the latest commit. The regular package is the latest release. I maintain only the regular package, but the git package is almost the same code.

**Comment by sharkwouter** [comment]
Makes sense that if some of the files already exist, that it would cause issues with the installation of the package. Glad you managed to fix it.

**Comment by sharkwouter** [comment]
I'll close this issue, because we don't officially support installing with python setup-tools.
