### ISSUE TITLE
Some games are shown twice (version 1.0.2, Arch Linux)

### ISSUE THREAD

**Issue by sluedecke** [sharkwouter/minigalaxy#324]
Two of my games are listed twice: Torchlight II (installed with mingalaxy) and Wasteland 2 DC (installed with offline installer before using minigalaxy).

Any idea how to solve this?

**Comment by sluedecke** [comment]
turns out Torchlight actually is Torchlight and Torchlight II both using the same game icon.

**Comment by sharkwouter** [comment]
Thanks for the report and the specific examples. I'll add it to the list for the next release.

**Comment by makson96** [comment]
I think this issue is duplicate of #142

**Comment by sharkwouter** [comment]
I'll keep this one open, since it mentions a specific game

**Comment by sharkwouter** [comment]
This should be fixed on master now
