### ISSUE TITLE
Not all purchased games are shown

### ISSUE THREAD

**Issue by itwasonlyabug** [sharkwouter/minigalaxy#330]
Hi, I gave minigalaxy a spin yesterday and I noticed that not all of my games are shown. I can see only 9 out of 16 and on Windows I see all of them.

I installed it from AUR - minigalaxy (bin). I tried reinstalling minigalay (manually purging any remaining files), but still get the same result. I don't see any errors or anything of the sort.

OS: Manjaro Linux x86_64 
Kernel: 5.12.8-1-MANJARO 
GNOME: 3.38

Thanks!

**Comment by FriedrichGaming** [comment]
Click the Menu-Button in the top right > Click on Settings > Enable the option called "show Windows-Games"

**Comment by itwasonlyabug** [comment]
I don't know how I missed that ... 🤦 Everything is top-notch now. Thank you!

**Comment by sharkwouter** [comment]
Great! Thanks for reporting back
