### ISSUE TITLE
Error opening game

### ISSUE THREAD

**Issue by nathansgithub** [sharkwouter/minigalaxy#336]
Hi,

I installed Dead Cells from inside Minigalaxy, but it gives me an error message when I try to run it. If I run the start.sh script in the game directory, it runs without any problems. And other games run fine from Minigalaxy.

I am running version 1.0.2 from a Flatpak install on Pop OS 21.04.

```
> flatpak run io.github.sharkwouter.Minigalaxy
Gtk-Message: 13:41:41.555: Failed to load module "appmenu-gtk-module"
Gtk-Message: 13:41:41.685: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/minigalaxy/ui/gametile.py", line 411, in set_proper_dlc_icon
    response = source.read_finish(async_res)
gi.repository.GLib.Error: g-io-error-quark: Operation not supported (15)
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/minigalaxy/ui/gametile.py", line 411, in set_proper_dlc_icon
    response = source.read_finish(async_res)
gi.repository.GLib.Error: g-io-error-quark: Operation not supported (15)
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/minigalaxy/ui/gametile.py", line 411, in set_proper_dlc_icon
    response = source.read_finish(async_res)
gi.repository.GLib.Error: g-io-error-quark: Operation not supported (15)
Failed to start Dead Cells:
Running Dead Cells
** ERROR ** Missing library libsndio.so.7.0
** ERROR ** Missing library libsndio.so.7.0
src/module.c(321) : FATAL ERROR : Failed to load library openal.hdll
```

**Comment by sharkwouter** [comment]
Thanks for the report. It seems like either the bundled libraries are not used or you're missing one. Try installing the openal library. Should be the ``libopenal1`` package.

**Comment by nathansgithub** [comment]
Thanks. I checked and I do already have that library installed. Also, I tried to install Minigalaxy via apt, and Dead Cells launched fine from there. It's just not working from the Flatpak install.

**Comment by sharkwouter** [comment]
Oh, that makes sense, I read over there part where you said it was a Flatpak installation. Great it works fine natively. Flatpak cannot use libraries from the system. You should report bugs related to the Flatpak version here: https://github.com/flathub/io.github.sharkwouter.Minigalaxy
