### ISSUE TITLE
Utilize innoextract to automate the installation process

### ISSUE THREAD

**Issue by CTalvio** [sharkwouter/minigalaxy#344]
Currently, minigalaxy runs the installer for windows games in wine to install them.

This entire process could be automated using "innoextract", a tool which bypasses the need to run the installer in wine, for software installers that were created using Inno Setup.

This is the homepage of the tool: constexpr.org/innoextract/

**Comment by CTalvio** [comment]
Oops, looks like there is pull request with basic functionality already. Sorry. Looking forward to that being implemented.

**Comment by sharkwouter** [comment]
I'm going to re-open this, as there is not really an issue for this specific feature yet, just one of the problems it would solve. Take a look at #313.

**Comment by sharkwouter** [comment]
This will be fixed in the next release. It has been addressed by #334
