### ISSUE TITLE
Game names from goggame.info and API can be different

### ISSUE THREAD

**Issue by makson96** [sharkwouter/minigalaxy#349]
As you can see on picture below:
![names](https://user-images.githubusercontent.com/1833284/129953372-cab6c29e-2ac6-41d7-a97e-c6ea137cd516.png)
Directory name is created from name from API, but after game is installed name is taken from installed files. This results in for example constant "update available" status. I am working on cleaver solution.

**Comment by sharkwouter** [comment]
Good catch, I had not been able to find why this was happening so far. Thanks!
