### ISSUE TITLE
Update translations for 1.1.0 release

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#369]
Currently the date for the release has been set to the 7th of November and the strings on master shouldn't change much anymore. So this would be the perfect time to update some translations.

We currently have the following translations in need of updates:

- [ ] Brazilian Portuguese
- [x] Dutch (@sharkwouter)
- [x] Finnish
- [ ] French
- [x] German
- [ ] Italian
- [ ] Norwegian Bokmål
- [x] Norwegian Nynorsk
- [x] Polish
- [x] Russian
- [x] Simplified Chinese
- [x] Spanish
- [x] Swedish
- [ ] Taiwanese Mandarin
- [x] Turkish
- [x] Ukrainian

I'll be tagging all people who've helped translating Minigalaxy before below. If anyone feels like updating one of these translations, please do. All help is welcome here.

**Comment by sharkwouter** [comment]
Tagging all translators here: @s8321414 @BlindJerobine @fuzunspm @thomasb22 @protheory8 @tim77 @EsdrasTarsis @ArturWroblewski @kimmalmo @LordPilum @juanborda @dummyx @Newbytee @jonnelafin @karaushu @heidiwenger

Now would be a good time for an update if you'd like to.

**Comment by tim77** [comment]
Latest version from `master` in Flathub `beta` channel [available](https://flathub.org/builds/#/builders/32/builds/61623) for testing. Could be safely installed on system without worrying to broke something, but please backup your user data provided by Minigalaxy if you already using Flatpak version. To install Minigalaxy dev pre-1.1.0 version:

```bash
$ flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
$ flatpak install --user flathub-beta io.github.sharkwouter.Minigalaxy
```

To run:

```bash
$ flatpak run io.github.sharkwouter.Minigalaxy//beta
```

**Comment by sharkwouter** [comment]
I forgot to tag @koraynilay for the Italian translation. Sorry about that.
