### ISSUE TITLE
Minigalaxy doesn't detect Linux Version of Wasteland 3

### ISSUE THREAD

**Issue by FlorianPB** [sharkwouter/minigalaxy#382]
Hello, I wanted to download and install Wasteland 3 from GOG with Minigalaxy, it only detects Windows version, but Wasteland 3 on GOG has a Linux version.

**Comment by FlorianPB** [comment]
Made GOG corrected their API issue for this game

**Comment by sharkwouter** [comment]
Great! Thanks for the update!
