### ISSUE TITLE
Hard WebKit dependency?

### ISSUE THREAD

**Issue by crabctrl** [sharkwouter/minigalaxy#389]
WebKit is a pretty heavy dependency, avoided by some systems due to performance and security concerns. Is there no chance of making the WebKit dependency optional, as is the case with similar tools such as `lgogdownloader`?

**Comment by waltercool** [comment]
Hi @sharkwouter, is Webkit only used at login screen?

If that's the case, I could make some tests to use minigalaxy just playing with ~/config/minigalaxy/config.json and provide some documentation for users who don't want WebkitGTK.

For now I can confirm just commenting Webkit2 dependency at login.py kinda works, while of course everything is messed up (but that's fine too).

As you mentioned, WebkitGTK should not be removed, but at least enough to avoid breaking if you have a correct "manual" configuration.
