### ISSUE TITLE
Add DLC installation options

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#4]

**Comment by Xvatten** [comment]
This will be very helpful for users. Even make minigalaxy more attractive.

**Comment by jenrus00** [comment]
Minigalaxy already has FPS counter, DLC installation will be another killer feature
I personally like Minigalaxy more than Lutris

**Comment by makson96** [comment]
I will take on this one. I have some early experiment in:
https://github.com/makson96/minigalaxy/tree/dlc-support
The idea is that nothing changes for menu for games without DLCs:
![normal_tile](https://user-images.githubusercontent.com/1833284/97103979-5b7e6f80-16b0-11eb-837c-70d04305b6a8.png)
But for games with DLCs, there will be additional submenu for DLCs:
![dlc_tile](https://user-images.githubusercontent.com/1833284/97103994-7224c680-16b0-11eb-8b3b-25206ed77096.png)
This submenu will have each row for every DLC.
Each row consists of three elements:
icon (dlc sidebar)
DLC Title
Button for download (which will be replaced by "OK" icon if DLC is already downloaded and up to date).

Please tell me if such a design is ok for you.

I am confident that I can handle it from Python code side, but I am not the best at Glade Gtk, so I could probably use some of your help it this regard. If specific question materialize, I will let you know.
Best regards,
Tomek

**Comment by sharkwouter** [comment]
That looks good, although I would put the DLC option above "Uninstall". Feel free to ask questions on Discord. Thanks for picking this up!

**Comment by sharkwouter** [comment]
The main thing I'm worried about with this would be the amount of API calls. Would it be possible to get is information in the same call which is being executed to check for updates?

**Comment by makson96** [comment]
Thanks for early feedback. Both of your concerns are already addressed in the branch.
I manage to figure out UI (it looks like Gtk was not that hard after all). At the moment it looks like this:
![dlc_tile2](https://user-images.githubusercontent.com/1833284/97117768-39afd780-1706-11eb-85c3-c4cd7bcebff0.png)
You can even click download button and dlc installer info will be printed to stdout.

Can you tell me if this branch affect minigalaxy initial load time a lot, or is it only my internet is so slow?

**Comment by makson96** [comment]
OK.
Branch now mostly works as I expect.
I just need to add some exception handling and clean some code and it will be good for merge:
![stellaris_dlc1](https://user-images.githubusercontent.com/1833284/97236057-91247500-17e4-11eb-8c5a-1a6588d3b949.png)
![stellaris_dlc2](https://user-images.githubusercontent.com/1833284/97236067-94b7fc00-17e4-11eb-892e-56cf34c2cd7e.png)

**Comment by sharkwouter** [comment]
Great, that looks good! I'm looking forward to the pull request. I haven't had time to look at the code itself so far unfortunately, but I'll make some time for it either today or on the weekend.

**Comment by sharkwouter** [comment]
I tested it for a little bit now. I don't know if I own any games with for which I own DLC. What I noticed so far is that the DLC button also appears if you do not own any DLC for the game and that it looks very different from the other buttons. I don't quit know how to test this, sorry about that.

**Comment by makson96** [comment]
in gametile.py in __check_for_dlc in second line of this function can you add "print(dlcs)". Lets see what is there in some of your games without dlcs.

**Comment by sharkwouter** [comment]
Support for installing DLC has been merged.
