### ISSUE TITLE
Czech translation file name

### ISSUE THREAD

**Issue by AsciiWolf** [sharkwouter/minigalaxy#409]
I am not sure whether the current [cs_CZ.po](https://github.com/sharkwouter/minigalaxy/blob/master/data/po/cs_CZ.po) file name is correct. Most other projects have "cs.po" as the Czech language name. Could someone please check this?

/cc @jakbuz23

**Comment by jakbuz23** [comment]
I belive it can be both. Either "cs.po" or full locale "cs_CZ.po". I have seen both.

**Comment by sharkwouter** [comment]
Both can work, but it will probably make sense to rename it. Are there more countries who use the Czech language?

**Comment by jakbuz23** [comment]
Only one country uses it officially.

**Comment by AsciiWolf** [comment]
It looks like that Minigalaxy 1.1.0 in Flatpak is still in English on my Fedora system with Czech locale:

![minigalaxy](https://user-images.githubusercontent.com/2339930/140931736-af9f063e-2bd9-4d87-9376-217203f2a16f.png)

**Comment by flagrama** [comment]
Could you post the output of the `locale` command in a terminal?

**Comment by sharkwouter** [comment]
Is this from source or did you install it? You might need to run ``scripts/compile-translations.sh`` or unset the LANG environment variable.

**Comment by AsciiWolf** [comment]
I am using a Minigalaxy Flatpak from Flathub. Here is my locale output:
```
LANG=cs_CZ.UTF-8
LC_CTYPE="cs_CZ.UTF-8"
LC_NUMERIC="cs_CZ.UTF-8"
LC_TIME="cs_CZ.UTF-8"
LC_COLLATE="cs_CZ.UTF-8"
LC_MONETARY="cs_CZ.UTF-8"
LC_MESSAGES="cs_CZ.UTF-8"
LC_PAPER="cs_CZ.UTF-8"
LC_NAME="cs_CZ.UTF-8"
LC_ADDRESS="cs_CZ.UTF-8"
LC_TELEPHONE="cs_CZ.UTF-8"
LC_MEASUREMENT="cs_CZ.UTF-8"
LC_IDENTIFICATION="cs_CZ.UTF-8"
LC_ALL=
```

**Comment by flagrama** [comment]
What about `echo $LANGUAGE` as well?

**Comment by AsciiWolf** [comment]
`$LANGUAGE` is empty. Did you mean echo `$LANG`? It returns: `cs_CZ.UTF-8`

Other apps are correctly translated.

**Comment by flagrama** [comment]
Nope, I meant `$LANGUAGE`. It is a variable that can cause issues with strings defined in Glade files being translated properly. `$LANG` was already in the other output.

Are the other apps that are correctly translated also Flatpak applications?

**Comment by AsciiWolf** [comment]
> Are the other apps that are correctly translated also Flatpak applications?

Yeah, many of them are.


> Also where did you get the 1.1.0 Flatpak? The one on Flathub looks to still be 1.0.2.

![minigalaxy_about](https://user-images.githubusercontent.com/2339930/141012651-3ddd0914-cade-4a4e-b89f-bc27c34d3c09.png)

**Comment by AsciiWolf** [comment]
Even when manually changing the language to "Czech" in Minigalaxy preferences, the app is still in English (I have tried restarting it):

![minigalaxy_prefs](https://user-images.githubusercontent.com/2339930/141013080-db623949-4369-43d5-9969-437bcbdf147e.png)

**Comment by AsciiWolf** [comment]
I think that this problem will be solved after renaming the cs_CZ.po to cs.po and changing "Language: cs_CZ\n" to "Language: cs\n" in that file.

**Comment by flagrama** [comment]
I don't think that's the issue at all, because with my LANG set to that locale, it seems fine
![image](https://user-images.githubusercontent.com/634079/141014700-c8fe06d8-ce9f-46d0-b172-e22abcbf5fb8.png)

**Comment by AsciiWolf** [comment]
Hmm, that is strange. It may be some bug in the Minigalaxy Flatpak.

**Comment by flagrama** [comment]
I'm not actually seeing where the flathub package runs `compile_translations` but I'm not familiar with flatpaks myself. If it only gets the source files and doesn't run that script though, it doesn't have any translations at all.

**Comment by AsciiWolf** [comment]
I have reported it downstream as a Minigalaxy Flatpak issue.

**Comment by AsciiWolf** [comment]
Closing this ticket since the localization not working seems to be an unrelated issue.
