### ISSUE TITLE
Changing installation path crashes the app

### ISSUE THREAD

**Issue by sigzegv** [sharkwouter/minigalaxy#412]
I install game in ~/.local/games, if I set this specific path in the app, it just crashes when retrieving game list :

> 
> Exception in thread Thread-157:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/lib/python3/dist-packages/minigalaxy/ui/library.py", line 47, in __update_library
>     self.games = self.__get_installed_games()
>   File "/usr/lib/python3/dist-packages/minigalaxy/ui/library.py", line 136, in __get_installed_games
>     info = json.loads(info_file.read())
>   File "/usr/lib/python3.8/json/__init__.py", line 337, in loads
>     raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
> json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

I don"t know where the issue comes from, some other paths doesn't crash the app. Maybe it's due because of directory content non empty ? or because it's a hidden directory. I don't know.

**Comment by sharkwouter** [comment]
Thanks for the report. Does this happen when you start the app or when you change the directory? How are you changing it?

In the quick test I did, I wasn't able to reproduce this, so I'm probably not taking the same actions.

**Comment by sigzegv** [comment]
It happens both when I change the directory first time from the settings (when validating the change), and then everytime I start the app (seems to be locked then).

**Comment by sharkwouter** [comment]
What does ``~/.config/minigalaxy/config.json`` look like? Could you paste it here?

What you can do to fix it is to start minigalaxy from the terminal with the ``--reset`` flag or to delete ``~/.config/minigalaxy/config.json``. That doesn't solve the problem in the application, but at least you'd be able to use minigalaxy again.

**Comment by sigzegv** [comment]
I'll tried to reset/delete the parameter multiple times, the issue always comes back when using this path.

**Comment by sharkwouter** [comment]
That's surprising. I'll look into this some more later. Thanks for reporting.

**Comment by sharkwouter** [comment]
Could you still post the content of ``~/.config/minigalaxy/config.json`` after changing it?

**Comment by sharkwouter** [comment]
Wait, does your username contain any special characters?

**Comment by makson96** [comment]
> I don"t know where the issue comes from, some other paths doesn't crash the app. Maybe it's due because of **directory content non empty** ? or because it's a hidden directory. I don't know.

I am guessing that this is a case and we are hitting some goggame info file which is encoded with utf-8-sig.

**Comment by sigzegv** [comment]
ty for the fix :)
