### ISSUE TITLE
Installation silently fails after download in linux

### ISSUE THREAD

**Issue by Szhmidty** [sharkwouter/minigalaxy#423]
Version 1.1.0, installed from the AUR

Games download fine, but installation never happens and no warning or error ever appears. You can press the download button again but it does nothing.

After downloading, there is an installation script under ~/.cache/minigalaxy/download/[game_name]/[installation_script_name].sh, and running it manually will install the game just fine. However, you need to chmod +x to give the script execution permission. Maybe that's related to why installation is failing in the first place?

It's possible this issue is Arch specific, or just something wrong with my system, as I don't experience this issue in Mint.

**Comment by flagrama** [comment]
Last time I saw this happen the user didn't have `unzip` installed. Minigalaxy explicitly uses `unzip` so if that isn't marked as a dependency on the AUR pkgbuild that might be an issue to bring up with the package maintainer.

**Comment by Szhmidty** [comment]
You're right, that was the issue, and unzip isn't listed in the AUR list of dependencies.
