### ISSUE TITLE
[Request] Customisable Download Cache

### ISSUE THREAD

**Issue by lumip** [sharkwouter/minigalaxy#424]
It would be great if there was an option to modify the download cache location in case the default location is on a drive that does not fit some game installers.

**Comment by sharkwouter** [comment]
You could change the XDG_CACHE_HOME or set it when launching. Try launching it like so: ```XDG_CACHE_HOME=/your/location minigalaxy```

**Comment by lumip** [comment]
Thanks, I'll try that
