### ISSUE TITLE
Wine wasn't found. Showing games cannot be enabled.

### ISSUE THREAD

**Issue by Mark12870** [sharkwouter/minigalaxy#425]
OS: Solus

I have a problem I can't enable "Show Windows games" in settings. When I'm trying to save the settings there will open dialog "Wine wasn't found. Showing games cannot be enabled.". I have the `wine` package installed.

Can please someone help me with debugging this?

**Comment by sharkwouter** [comment]
There needs to be a ``wine`` command in your path, otherwise it doesn't work. What's the output of ``which wine``?
