### ISSUE TITLE
Innoextract does not respect the game language set in Preference

### ISSUE THREAD

**Issue by Kzimir** [sharkwouter/minigalaxy#427]
Hello,

This issue does not affect new games because it's now possible to change the language directly in-game. For old game as "XCom Enemy Unknow : Complete Edition", there is no option in-game to change the language. 

In fact for this game when you install it with Wine, the language must be changed at the beginning in the setup option : 
[https://postimg.cc/VrVqY6C5](https://postimg.cc/VrVqY6C5)
For example, Vampyr and Dragon Age : Origins Ultimate Edition have not this option because the language can be changed directly in game.

If MiniGalaxy extract the game with Innoextract, all languages are extracted and for XCom EU, the game's language by default is Chinese. To change the language, you need : 
```
- Launch the game once.
- Go to ~/Documents/My Games/XCOM - Enemy Unknown/XComGame/Config (in my case)
- Edit "XComEngine.ini" file and change "Language=" line.
```

The good news is that innoextract can list the languages supported by the installer.
```
kasimir@debian-desktop:~/Jeux/XCOM Enemy Unknown/$ innoextract setup_xcom_enemy_unknown_401776_\(19762\).exe --list-languages
Inspecting "XCOM - Enemy Unknown" - setup data version 5.5.7 (unicode)
 - de-DE
 - en-US
 - es-ES
 - fr-FR
 - it-IT
 - ja-JP
 - ko-KR
 - pl-PL
 - ru-RU
 - zh-Hant
Done.
```

There is an option with innoextract to extract only a specific language : `--language ARG`
I extracted XCom game like this : 
`innoextract setup_xcom_enemy_unknown_401776_\(19762\).exe -d XCom --language fr-FR`
and at the 1st launch (after to delete XCom option folder in ~Documents), the game is correctly in French.

For game which have not language option in the setup like Vampyr or Dragon Age Origins, the `--list-languages`command returns only **en_US**

I think we need to create a function which check if the setup has more languages but only for game which have only english in installer['language'] to avoid potential issues. (see [here](https://github.com/sharkwouter/minigalaxy/blob/6d5cb94c14637a37139e7c87cfa08c37f9e2f963/minigalaxy/api.py#L158))

**Comment by sharkwouter** [comment]
Thanks for the really detailed report. Seems implementing this might be a bit harder than I thought, though, since there are more languages available for that game than we currently have in the preferences. We should probably ask the user to choose the language upon install.

**Comment by makson96** [comment]
Thanks for the issue report.
I personally would still prefer innoextract more than wine. The language issue seems to be serious one though.
Maybe we should explore possibility to extract language set in preferences and if it is not available extract English instead?
