### ISSUE TITLE
Prefer Wine instead of Innoextract for Windows games

### ISSUE THREAD

**Issue by Kzimir** [sharkwouter/minigalaxy#428]
Hello,

I write this message to explain why i think it's preferable to choose Wine instead of Innoextract to install Windows games.

1- It's impossible to install patch with Wine if the game has not installed with it. Because some entries are added in the Wine Registry (Regedit) after installation to localize the install path. 

With "The Witcher 3 : GOTY", the offline setup install the 1.31 version and there is a patch to update the game to 1.32. Firstly, MiniGalaxy does not detect that a patch is available and secondly, if i try to install the patch manually with Wine, i have this error : 
https://postimg.cc/qg2S2KXx

2- Install Fallout 3 or Fallout New Vegas with innoextract prevents playing because the game's launcher think the game is not installed. 
https://postimg.cc/cgnj9tqZ

3- GoG has over 3000 games, and the setup installer can be different between more games. I have 15 games in my GoG library and the innoextract installation from MiniGalaxy works for 14 games... It does not work for Dragon Age : Origins because the installer needs to pass `--gog` argument to the innoextract command + the game is extracted in a folder named "game"
--> So the innoextract function must be rewrite to support this type of installer. And i don't know if there are others type ...

4- See the bug report that i opened yesterday #427 

I don't know if these points can change something but i'm agree that innoextract is more quick and easy than wine to install Windows games but in my case, i think that all these points are critical ... It's the main reason that i use minigalaxy git and modify "Installer.py" to choose Wine instead of Innoextract.

**Comment by sharkwouter** [comment]
Thanks again for the detailed report. While I see the problems, I do disagree with this. Innoextract solves a lot of issues which cannot be solved easily with the wine installer. What I'd prefer to do is have a list of applications which do not work with Innoextract and use th gog option by default.

**Comment by Kzimir** [comment]
So point 1 & 2 will be never fixed... Good luck with that

**Comment by sharkwouter** [comment]
We currently do not update with patches, but by redownloading the installer. GOG does update the installers, so this should work. A user manually applying a patch should not happen.

The Fallout games can be exempt from having to be installed using wine. I do wonder how Steam solves the problems with these games now, they also do not run an installer and instead just download the files.

**Comment by Kzimir** [comment]
Steam and Galaxy don't have this issue when it download the files instead of installer ...
That's why implement this solution can be benefit ...
