### ISSUE TITLE
Minigalaxy Won't Launch

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [sharkwouter/minigalaxy#431]
I hope you're having a good day.

I ran OS updates recently and now minigalaxy will not launch. I believe I have minigalaxy 1.1.0 installed. Below is the message I get when I try to launch minigalaxy from the terminal. Let me know what information would be useful.

>Traceback (most recent call last):
  File "/usr/bin/minigalaxy", line 16, in <module>
    from minigalaxy.version import VERSION
ModuleNotFoundError: No module named 'minigalaxy'

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
I am on Arch and took a guess that I needed to rebuild from newer packages now on my system. So I deleted my previously built minigalaxy package and rebuilt from AUR and reinstalled; it works now.

**Comment by sharkwouter** [comment]
Glad you solved it
