### ISSUE TITLE
Can't connect GOG server on debian bullseye

### ISSUE THREAD

**Issue by paulvera31490** [sharkwouter/minigalaxy#445]
On my debian bullseye, I launch minigalaxy installed with bullseye package. I enter my valid login and password for GOG, the minigalaxy displays the messages "Impossible de récupérer la bibliothèque" "Impossible de se connecter aux serveurs de GOG" which can be translated in english by "impossible to retrieve the library" "Impossible to connect to GOG servers"

Remark 1 : I haven't found any log for minigalaxy
Remark 2 : I changed in "preferences" language to "english" but messages are stills displayed in french (the language of this user in linux) 
Remark 3 : I'm correctly authenticated, I can see my user name in the title bar of the main screen

**Comment by sharkwouter** [comment]
@paulvera31490 thanks for reporting this and sorry for the very late response to this one. If you're still around, could you try if the recently released version 1.2.1 resolves this issue?
