### ISSUE TITLE
Fail to "start slay the spire"

### ISSUE THREAD

**Issue by RockEater** [sharkwouter/minigalaxy#462]
Not sure how to mark it as a bug
![Bug_report](https://user-images.githubusercontent.com/36081420/153772147-0c4893ae-534e-4eea-a5f9-38e70e756202.png)

the game does work when I launch so it's not critical to me, but it would be good to inform

**Comment by lmeunier** [comment]
Same error here when starting Slay the Spire, but I get the error both with minigalaxy and the `./start.sh` script provided in the downloaded archive.

Are your sure you are using the `./start.sh` script when launching it manually?

Anyway, this script is bugged (see: https://www.gog.com/forum/slay_the_spire/linux_starter_is_bugged). You have to replace line 20 with :
```
 ./"jre/bin/java" -jar desktop-1.0.jar
```

Doing this, the game starts now without error when launched from minigalaxy.

**Comment by RockEater** [comment]
Yeah, forgot about this message, the error did seem to be with the game, thank you for the response
