### ISSUE TITLE
Stardew Valley started from MiniGalaxy(FlatPak on SteamDeck) don't see it's save files

### ISSUE THREAD

**Issue by isopix** [sharkwouter/minigalaxy#468]
Stardew Valley started from MiniGalaxy(FlatPak on SteamDeck) don't see it's save files

When started directly from start.sh it does.

I guess that more games are affected.

**Comment by sharkwouter** [comment]
This makes sense. The Flatpak keeps its own save files. I would report this to the GitHub repositoy for the flatpak itself: https://github.com/flathub/io.github.sharkwouter.Minigalaxy
