### ISSUE TITLE
OpenSUSE 15.1 error on install:  python3-gobject >= 3.30 required

### ISSUE THREAD

**Issue by RafaelLinux** [sharkwouter/minigalaxy#47]
OpenSUSE 15.1 with python3-gobject 3.26.1 installed.
After doing `sudo zypper in minigalaxy`, system give me an error:
`Nothing provides python3-gobject >= 3.30, neccesary for minigalaxy-0.9.1-lp151.3.1.noarch`
so I can't continue installing.

Please, any idea?

Thank you

**Comment by sharkwouter** [comment]
Unfortunately the required version of python3-gobject is not available in openSUSE 15.1. It will be in 15.2 and is already available in Tumbleweed.

**Comment by RafaelLinux** [comment]
Unfortunately, Tumbleweed is a rolling release, and I prefer to run only the  stable version.
Thank you
