### ISSUE TITLE
Powerslave (Original) doesn't show in minigalaxy

### ISSUE THREAD

**Issue by LukasThyWalls** [sharkwouter/minigalaxy#479]
Powerslave (original version/DOSBox [https://www.gog.com/game/powerslave](https://www.gog.com/game/powerslave)) doesn't show in minigalaxy, but it have linux version:

![PowerslaveOriginal_GOGLibrary](https://user-images.githubusercontent.com/1467366/162639181-0e9fe791-fbca-4cdc-88e5-cc6e10d655a8.png)

Other games purchased before and later appear, but not this one.

Thanks.

**Comment by sharkwouter** [comment]
Thanks for the report. This is probably a bug in the API. I don't own this game, so it's a bit hard to confirm, though. Have you reported this to GOG?

**Comment by LukasThyWalls** [comment]
> Thanks for the report. This is probably a bug in the API. I don't own this game, so it's a bit hard to confirm, though. Have you reported this to GOG?

It shows fine in Galaxy and also all info is in [GOGdb.org](https://www.gogdb.org/product/2132611980).

However, i just tested something: if you filter all your games by system = Linux, Powerslave doesn't show although it has Linux version, so maybe that is.

I will contact GOG, and leave this open until i see it's fixed, just in case someone else have an issue with this one or other for similar reasons.

Thanks.

**Comment by sharkwouter** [comment]
Thanks! I think that's it. GOGdb also doesn't show Linux in "Content system compatibility".

**Comment by LukasThyWalls** [comment]
I contacted GOG and they fixed the issue. Now Powerslave appears in minigalaxy.

Thanks!

Closed.
