### ISSUE TITLE
Dependency not satisfiable on Mint 19.3

### ISSUE THREAD

**Issue by edgagne** [sharkwouter/minigalaxy#51]
Using the .deb from the downloads page, I get the following error message "Error: Dependency is not satisfiable: python3-gi (>=3.30)" when trying to install on Mint 19.3. 

Mint defaults to Python 2.7 so that is the obvious issue. However, Python 2.7 and 3.6 are both installed. I'm dis-inclined to change the default version as that will cause issues with system scripts (and much bigger headaches). I have no problem switching distros (or waiting for future releases; this is a beta after all). However, this issue will probably affect others and (I'm hoping) isn't too hard to fix or post a work-around for.

Also, **Ubuntu 18.04 _should_ have the same problem** (but I haven't tested) since Mint's python setup is _to the best of my understanding_ due to the Ubuntu base. 

PS -- really appreciate all the effort that has gone into this project so far!

**Comment by sharkwouter** [comment]
Unfortunately, a feature which wasn't introduced until python3-gi version 3.30 is very important to run Minigalaxy. It works on any system based on Ubuntu 18.10 or newer.

**Comment by arrowgent** [comment]
sorry for commenting through this closed topic

i have unpackaged the .deb installer and put it in /opt/minigalaxy
then sym linked the particular required files to /usr folders where required
everything generally seems to work fine

although i agree, the one dependency it requires will refuse to install on 18.04/19.3

so im not sure what dependency it requires that is "very important"

**Comment by sharkwouter** [comment]
It's Pygobject which is too old. On older versions of Ubuntu you can't start Minigalaxy because of this. It can be solved by installing it with pip, but I'd rather not recommend to users to mess with their system in that way.
