### ISSUE TITLE
Wine settings and also an ability to run an arbitrary executable in wine prefix

### ISSUE THREAD

**Issue by eternal-sorrow** [sharkwouter/minigalaxy#516]
Would be great to be able to open wine settings in some way (`winecfg.exe` at the very least).

Also, I wanted to install Heroes 3 HD mod on top of my Heroes 3 Complete game installation and was unable to do that.

**Comment by sharkwouter** [comment]
It is already possible to open wincfg in the prefix a wine game is installed. It's available in the game's preferences window.

**Comment by sharkwouter** [comment]
This should be available in the new version 1.2.1 release.
