### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by chainedghost** [sharkwouter/minigalaxy#520]
The latest update on Arch (1.2.1) causes Minigalaxy to constantly use one full core of CPU usage.
I am using Plasma on AMD hardware.

**Comment by sharkwouter** [comment]
Thanks for reporting this. Lets see if we can figure out the cause. How many games do you have installed?

**Comment by chainedghost** [comment]
I have six games installed.

**Comment by sharkwouter** [comment]
Okay, then it's a bit odd. What kind of hardware do you have?

**Comment by chainedghost** [comment]
5950X and 6900XT on my desktop and 3800U on my Thinkpad.

**Comment by sharkwouter** [comment]
I've just pushed a commit which should resolve this. Would it be possible for you to test what's on the master branch?

**Comment by chainedghost** [comment]
That fixed it!

**Comment by sharkwouter** [comment]
Thanks for confirming it works!

**Comment by chainedghost** [comment]
Thanks for addressing it so quickly!
