### ISSUE TITLE
Please set proper version in version.py for releases

### ISSUE THREAD

**Issue by stephanlachnit** [sharkwouter/minigalaxy#531]
Having `VERSION = "git"` in `minigalaxy/version.py` all the time kinda makes it a bit useless - while I see that this should be adjust in `create-release.sh`, this did not happen for 1.2.0 and 1.2.1.

**Comment by sharkwouter** [comment]
So, the intent was that packagers would set the version in version.py from now on, but I initially forgot to add that to the release notes. I'm sorry for that. In hindsight, it's just causing confusion and extra work for packagers. I'll re-add a version for the next release.

**Comment by sharkwouter** [comment]
This will be fixed in the next release. I've added it to the release commit now. Sorry for the inconvenience.
