### ISSUE TITLE
Option for .desktop-files

### ISSUE THREAD

**Issue by hodasemi** [sharkwouter/minigalaxy#54]
When you install a game via the installer script you can create .desktop files on desktop and for the application menu. It would be nice to have this choice too, or add desktop files afterwards via a button.

**Comment by sharkwouter** [comment]
That's a good idea, I'll look into it when I have time for it. At the moment some other things have my attention

**Comment by sharkwouter** [comment]
For now I'm going to remove this from the 1.0.0 milestone, because that will be the name of the new release which is coming up and this feature has not yet been implemented.

**Comment by sharkwouter** [comment]
This has been implemented in 1.1.0, even though I forgot to add it to the changelog. Oops...
