### ISSUE TITLE
Change language per game?

### ISSUE THREAD

**Issue by swsnr** [sharkwouter/minigalaxy#540]
Minigalaxy lets me set my preferred language for games globally, but can I also set this per game before downloading and installing a game?

I mostly prefer English, but for some games the original German or the German translation is much better.

If it's not possible, never mind.  If it's possible to implement this, perhaps I'll find the time to make a merge request 🙂

**Comment by swsnr** [comment]
I'm no longer using minigalaxy, so I'm closing this ticket 🙂

**Comment by sharkwouter** [comment]
That's no problem, thanks for reporting anyway. I do think it's a good idea. I'll recreate the issue on my name.
