### ISSUE TITLE
[Feature Request] User Categories for GOG games

### ISSUE THREAD

**Issue by dtantono** [sharkwouter/minigalaxy#543]
With big libraries, especially with the games from GOG, it can be really hard to browse the library and Ability to create and manage categories like Steams collections is very useful. What do you think?

**Comment by sharkwouter** [comment]
That's a good idea, thanks! Will see if I manage to get to this at some point. PRs for this would be welcome too.

**Comment by orende** [comment]
@dtantono I'm interested in implementing something like this as I could use this feature as well. But just to clarify what you mean, did you imagine something like:

1. selecting multiple genres and then getting a filtered list of games _or_
2. creating named groups of games (similar to Steam's collections) and filtering the list of games with them?

**Comment by dtantono** [comment]
I think basic named group collection like Steam will be nice

**Comment by sharkwouter** [comment]
I can elaborate a little bit on this one. Each game has categories already assigned to it in the GOG API. I think being able to search for them might be nice. I'm not sure if Gnome supports search suggestions.

**Comment by orende** [comment]
Right, I'll start off simple with just getting game categories from GOG and adding filtering functionality using that data, and once that's done and merged I can start looking into replicating something like Steam's dynamic collections based on categories.

As for search suggestions, it seems there's a auxiliary object named Gtk.EntryCompletion that can be used in conjunction with the Gtk.Entry component to enable input suggestions.

**Comment by sharkwouter** [comment]
@orende that sounds good to me. I would save the categories in Game objects. Good find on the search suggestions.

I would say something like Steam's dynamic collections should be a separate issue. I'm not exactly sure what that would look like, though.

**Comment by orende** [comment]
@dtantono If you use the master branch version of the client, you can try this feature out now.
