### ISSUE TITLE
Jagged Alliance 2: Wine extraction failed

### ISSUE THREAD

**Issue by swsnr** [sharkwouter/minigalaxy#547]
I'm using the [flatpak package of Minigalaxy](https://flathub.org/apps/details/io.github.sharkwouter.Minigalaxy).  When installing Jagged Alliance 2 I get a "Wine extraction failed" error, with no further details.

I tried running with `MG_DEBUG=1`, but this did not reveal more details in the logs.  What can I do to debug this issue?

I checked the code, and it looks as if minigalaxy discards the stdout and stderr of the wine process; perhaps logging could be improved here?

**Comment by swsnr** [comment]
I no longer use minigalaxy, so I'm closing this issue to get it off my issues list.

**Comment by sharkwouter** [comment]
No problem, I recreated the issue
