### ISSUE TITLE
Feature Request: Donate Button

### ISSUE THREAD

**Issue by Snuzzums** [sharkwouter/minigalaxy#567]
You guys do awesome work, and I'd like to donate. I understand that stripe charges a fee, as does paypal and others, so if you could also post the fee next to the donate button, along with a minimum donation, that would be great. Without a minimum donation, you guys will end up paying more in fees than getting donations.

Thanks ahead of time,
-Hamdrew

**Comment by sharkwouter** [comment]
I appreciate the sentiment, but I have a couple of reasons for not wanting people to donate. I'd have to ask my employer for permission to receive donations, doing taxes become more annoying and I think it would add some extra pressure. Taking donations doesn't seem worth doing for me personally at the moment. I'm glad you appreciate Minigalaxy, though. Thanks for using it!
