### ISSUE TITLE
Divinity Original Sin: Profile gone after quitting and restarting minigalaxy from flatpak

### ISSUE THREAD

**Issue by ArneBab** [sharkwouter/minigalaxy#568]
I can run and play Divinity Original Sin Enhanced Version (version 1), but after stopping and restarting Minigalaxy 1.2.2 the profile is gone along with all savegames.

I run minigalaxy 1.2.2 from flatpak on a Guix System.

**Comment by lmeunier** [comment]
It seems your issue is related to https://github.com/flathub/io.github.sharkwouter.Minigalaxy/issues/19
Should be fixed by https://github.com/flathub/io.github.sharkwouter.Minigalaxy/pull/5

**Comment by ArneBab** [comment]
It looks like it — thank you!

**Comment by sharkwouter** [comment]
I'm going to close this one, because it's a Flatpak specific issue and I do not manage the Flatpak build. Thanks for reporting, though, it's appreciated nonetheless.
