### ISSUE TITLE
Error when trying to start from shortcut

### ISSUE THREAD

**Issue by Zalexanninev15** [sharkwouter/minigalaxy#578]
![image](https://github.com/sharkwouter/minigalaxy/assets/51060911/810a7a8b-b47d-4e9e-846e-74ae7db8e332)

It is launched only from under the terminal and only manually. Through bash, the script writes the error above.

![image](https://github.com/sharkwouter/minigalaxy/assets/51060911/36728c67-efe6-4a09-a0fe-a556884c2834)

**Comment by sharkwouter** [comment]
This seems to be an issue with reading the configuration. I've added some error handling to make sure this does not cause the configuration to not work at all anymore. I'm doing a release right now, so you'll be able to test if Minigalaxy 1.2.3 resolves the issue for you.

**Comment by Zalexanninev15** [comment]
Can you generate an RPM package for Fedora 38 for release?

**Comment by sharkwouter** [comment]
I am not a Fedora user, so I don't really know how packages for it are made. Contributions are welcome, though. I'd expect the new release to get in Fedora pretty soon.
