### ISSUE TITLE
Stellaris not installing

### ISSUE THREAD

**Issue by NonMeme** [sharkwouter/minigalaxy#586]
I own Stellaris through GOG. Last year and earlier this year, I had no trouble installing it on systems and updating it, but since yesterday, I could not download the new Astral Planes DLC. So, I uninstalled the whole game and I am trying to reinstall it. However, it seems to not work and shows "in queue" with no progress bar.

Here is the relevant Terminal code.

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/gametile.py", line 218, in __download_game
    result = self.__download(download_info, finish_func, cancel_to_state)
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/gametile.py", line 239, in __download
    total_file_size += int(self.api.get_file_size(file_info["downlink"]))
  File "/usr/lib/python3/dist-packages/minigalaxy/api.py", line 178, in get_file_size
    return root.attrib["total_size"]
KeyError: 'total_size'

**Comment by sharkwouter** [comment]
Thanks for reporting! I tried to reproduce this, but I wasn't able to with the games I own. Unfortunately I cannot test Stellaris. It would be good to know what the API returns for this. I've not seen a response where total_size is missing before. Maybe it is DLC specific.

**Comment by NonMeme** [comment]
> Thanks for reporting! I tried to reproduce this, but I wasn't able to with the games I own. Unfortunately I cannot test Stellaris. It would be good to know what the API returns for this. I've not seen a response where total_size is missing before. Maybe it is DLC specific.

Is there a way I can retrieve it? It doesn't work for the entire game, either. Not just that one DLC package.

**Comment by sharkwouter** [comment]
You could run Minigalaxy like this:
```
MG_DEBUG=1 minigalaxy
```
Do be a bit careful with copying the output, there are also going to be credentials in the early requests.

**Comment by NonMeme** [comment]
> You could run Minigalaxy like this:
> 
> ```
> MG_DEBUG=1 minigalaxy
> ```
> 
> Do be a bit careful with copying the output, there are also going to be credentials in the early requests.

What do I do from here? Try to install Stellaris itself? And copy something from this text and send it to you if it fails?

**Comment by sharkwouter** [comment]
Yeah, when you click install on stellaris, it should start printing the requests.

**Comment by NonMeme** [comment]
The game is still not installing. What should I do now?

**Comment by NonMeme** [comment]
This issue is resolved for me now.

**Comment by sharkwouter** [comment]
Oh, that's interesting. Thanks for the link. I took a quick look at it before and didn't see anything weird, so I wasn't sure what to do with it. Sorry for not updating earlier. This ended up on the back burner for me.
