### ISSUE TITLE
Remove/ change installation instructions for Gentoo

### ISSUE THREAD

**Issue by Mikrotherion** [sharkwouter/minigalaxy#588]
The latest ebuild in the metahax repository is 1.0.2 and won't merge because the ebuild manifest and the checksum don't match.
The repology plugin shows that there is a newer (1.1.0) ebuild in the GURU overlay, but that one is still rather old.
So either remove the reference to Gentoo completely or update the repository to install from to GURU.
Thanks.

**Comment by sharkwouter** [comment]
Thanks for the feedback, I'll remove it, since I cannot fix it myself. PRs are welcome, though.
