### ISSUE TITLE
[Suggestion] Add support for installing Windows games

### ISSUE THREAD

**Issue by BackOrder** [sharkwouter/minigalaxy#6]
Only 16 games out of 27 show up in minigalaxy. Any way to provide logs or something to help you guys to diagnostic the problem?

**Comment by sharkwouter** [comment]
Are all your games available for Linux? It should only list games which have a Linux download.

Could you name some games which do not show up? Then I'll look into it.

**Comment by BackOrder** [comment]
You are correct. It doesn't list games that are not for Linux. My expectation would be something lik GameHub where everything is listed and downloadable. GameHub even uses Proton to run Windows games. I suppose this would be a feature request then. :)

**Comment by sharkwouter** [comment]
No problem, I'll rename the issue and keep it open. It will probably not be a feature that will make it into version 1.0.0, though, there are still a lot of bugs to squish 😅

**Comment by EsdrasTarsis** [comment]
> No problem, I'll rename the issue and keep it open. It will probably not be a feature that will make it into version 1.0.0, though, there are still a lot of bugs to squish

But is there any implementation made with Wine? If yes, you could publish to the repository on another branch.

**Comment by btegs** [comment]
Maybe also bundle Proton GE by default? :-)

https://github.com/GloriousEggroll/proton-ge-custom/releases

**Comment by sharkwouter** [comment]
Today @Odelpasso and I finished up the wine support, which is now available on the master branch. It's not yet in an official release, though.

**Comment by radek-sprta** [comment]
I've tried two Wine games. Both of them installed fine. One of them did not launch, but that seemed to be an issue with Wine itself.

**Comment by sharkwouter** [comment]
Great, thanks for testing

**Comment by btegs** [comment]
Is this standard Wine or Wine though Proton?

**Comment by sharkwouter** [comment]
It's standard wine. That was easier to implement and available for more systems.

**Comment by sharkwouter** [comment]
Version 0.9.4 was just released, which has this feature
