### ISSUE TITLE
Current minigalaxy 1.3.0 seems to somehow corrupt the wine prefixes

### ISSUE THREAD

**Issue by ell1e** [sharkwouter/minigalaxy#602]
Just some months ago, I managed to install and run most games, [other than DOS due to that other unresolved issue](https://github.com/sharkwouter/minigalaxy/issues/592) using minigalaxy just fine. But with the current version 1.3.0, somehow it seems to break the wine prefixes after it managed to run the GOG.com installer just fine, leading to me being unable to launch the game with either no reaction to the play button or strange errors popping up:

![Screenshot_20240613_213310](https://github.com/sharkwouter/minigalaxy/assets/64124388/e8f29349-1c1b-4dba-bf50-6b81793b29b9)

Now if it was just one game affected I would just reinstall it, assuming a weird lightning in a bottle rare glitch, but *all* regular Windows games seem to be affected. Winecfg won't launch either for any of them. On the host system outside of flatpak, wine is installed both as a 64bit and 32bit version. I couldn't think of any obvious reason why this would be happening, so is this a minigalaxy regression of some sorts?

**Affected minigalaxy version:** 1.3.0

**Affected on linux distro:** openSUSE Slowroll

**Install method for minigalaxy:** flathub/flatpak

**Comment by sharkwouter** [comment]
Odd, seems like a flatpak specific issue. Could you report this to the flatpak repo?

**Comment by ell1e** [comment]
Sadly, combined with #592 it seems like in practice, it's not possible to launch any games anymore no matter which type. I reported that other one to the flatpak but there wasn't much of a reaction.

Is there a different distribution independent install method for minigalaxy that works?

**Comment by ell1e** [comment]
This seems to have been fixed somehow, perhaps #615 or something similar was related to this.
