### ISSUE TITLE
Can't download / install games

### ISSUE THREAD

**Issue by Hawkeye0021** [sharkwouter/minigalaxy#70]
Hello,
I'm trying to package minigalaxy for Solus. Everything builds and installs without issue, however when trying to download a game it skips to installing and hangs. When running through the terminal I get this after clicking the download button, regardless of the game.

```
hawkeye@desktopsolus ~/b/s/minigalaxy (master)> minigalaxy
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/site-packages/minigalaxy/window/gametile.py", line 132, in __download_file
    self.__install_game()
  File "/usr/lib/python3.7/site-packages/minigalaxy/window/gametile.py", line 151, in __install_game
    with zipfile.ZipFile(installer_path) as archive:
  File "/usr/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

```

**Comment by sharkwouter** [comment]
I'm seeing the same thing, that is odd. Thanks for reporting

**Comment by sharkwouter** [comment]
I found the problem. The GOG download servers return a 429 error and the following html when a gamefile is being downloaded:
```
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>GOG.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

        <!-- TODO: add favicons -->

    	<style type="text/css">
			html,
			body { height:100%; }
			body { margin:0; padding:0; 
				background-color:#ccc;
				background-image:-moz-linear-gradient(top, #bdbdbd, #ccc);
				background-image:-o-linear-gradient(top, #bdbdbd, #ccc);
				background-image:-webkit-linear-gradient(top, #BDBDBD, #ccc);
				background-image:linear-gradient(to bottom, #BDBDBD, #ccc);
				background-size:100% 486px; background-position:50% 0; background-repeat:repeat-x;
				color:#262626;
				font-family: 'Open Sans', sans-serif; 
			}
				.wrapper { display:table; 
					max-width:50em; height:100%; padding:0 5%; margin:0 auto;
				}
					.content { display:table-cell; 
						vertical-align:middle; 
					}
						p { margin-top:1em; font-size:1.2em; line-height:1.5; text-align:justify; }
						h1 { font-weight:300; font-size:2em; }
    	</style>
    </head>
    <body>
		<div class="wrapper">
			<div class="content">
				<p>
					We have temporarily blocked your access to our website because You have exceeded number of simultaneous connections. Sorry for any inconvenience this may cause.
				</p>
				<p>
					If you see this message very often, please contact our Support Team immediately after you are able to access GOG.com normally.
				</p>
			</div>
		</div>
    </body>
</html>
```
I'm pretty sure GOG just shut down all GOG clients for Linux just now. Lutris is not able to download from GOG anymore either.

**Comment by Hawkeye0021** [comment]
Full disclose that I know nothing about any of that, I just know an error when I see one :P But anyways

`<p>
					We have temporarily blocked your access to our website because You have exceeded number of simultaneous connections. Sorry for any inconvenience this may cause.
				</p>
				<p>
					If you see this message very often, please contact our Support Team immediately after you are able to access GOG.com normally.
				</p>`

Yeah sounds like whatever method was being used to download games from their servers has been blocked and you should take it up with support. That statement makes it sound like it's being treated like a regular user account? So it got blocked because it was making too many connections. Just a layman's perspective if it's any help.

**Comment by sharkwouter** [comment]
I managed to resolve this in the master branch. I'm not using the same session for all requests.

**Comment by Hawkeye0021** [comment]
Excellent! Just need to wait for a new release then and I can submit a new patch for Solus, thanks :D

**Comment by sharkwouter** [comment]
I'm going to close this for now, so I have a better overview of what still needs to be done. I will be doing a release next Tuesday which will include the fix for this issue.
