### ISSUE TITLE
Opening Preferences when downloading cancels the download

### ISSUE THREAD

**Issue by ToughGuyKunio** [sharkwouter/minigalaxy#8]
Opening _Preferences_ when downloading cancels the download.

Tested on Manjaro.

**Comment by sharkwouter** [comment]
Thanks for reporting. I can reproduce the error. I'll see if I can fix it.

**Comment by sharkwouter** [comment]
This has been fixed on the master branch now. It will be in the next release.

**Comment by sharkwouter** [comment]
I've released [version 0.9.1](https://github.com/sharkwouter/minigalaxy/releases/tag/0.9.1) now, which should solve this issue. Please re-open if you see it again.
