### ISSUE TITLE
Make installable through pip

### ISSUE THREAD

**Issue by goodevilgenius** [sharkwouter/minigalaxy#85]
Since distribution packages can sometimes lag behind, it would be useful if minigalaxy were installable through `pip`, so we could manually update as soon as possible.

I tried this when cloning the repo, by doing `pip install .`, but when doing that, and running `minigalaxy`, I get the error: `gi.repository.GLib.Error: g-io-error-quark: Error opening file /usr/share/minigalaxy/ui/login.ui: No such file or directory (1)`

It seems the files were actually installed under `/usr/local/share` rather than `/usr/share`. It may be that simply fixing the paths would resolve this issue.

**Comment by sharkwouter** [comment]
Good idea, I've seen multiple people have issues with this when installing in ways which I initially didn't expect. Supporting this would probably be quite easy, but requires I use a path relative to the executable. Lets see if I can make this work.

**Comment by sharkwouter** [comment]
If you pull from master, it should work now.
