### ISSUE TITLE
Seg fault with AUR package

### ISSUE THREAD

**Issue by LiamDawe** [sharkwouter/minigalaxy#9]
Not sure what I did wrong here, I launched it and accidentally clicked download on something (needs a confirmation!). Then I think I clicked it again and then the app just quit. Now it won't launch and all it tells me in terminal is:

> [liam@liam-manjaro ~]$ minigalaxy
Segmentation fault (core dumped)

**Comment by LiamDawe** [comment]
I removed the config file, then ran it again and came to this:

> [liam@liam-manjaro ~]$ minigalaxy
> *** BUG ***
> In pixman_region_append_non_o: The expression y1 < y2 was false
> Set a breakpoint on '_pixman_log_error' to debug
> 
> *** BUG ***
> In pixman_region_append_non_o: The expression y1 < y2 was false
> Set a breakpoint on '_pixman_log_error' to debug
> 
> *** BUG ***
> In pixman_region_append_non_o: The expression r->x1 < r->x2 was false
> Set a breakpoint on '_pixman_log_error' to debug
> 
> double free or corruption (!prev)
> Aborted (core dumped)

**Comment by sharkwouter** [comment]
I was hoping I had fixed this issue before launch.I've been chasing these crashes for 5 days now, but the error messages seem different every time and it's never a python error. This makes it hard to troubleshoot. I'll keep you posted.

So far, I think it is most likely that unzip fails sometimes or that PyGObject doesn't like it if you modify Gtk Widgets in a different thread. I'll do some more debugging

**Comment by sharkwouter** [comment]
My guess it that it crashed while it was still downloading thumbnails and it left one of the thumbnails in an unreadable state. It's a bit weird though. I'd say the first crash is the main problem.

I've been debugging some crashes for a couple of days now, but it is really hard to figure out what is going on. I'm not getting any python errors. I'll keep you posted.

**Comment by sharkwouter** [comment]
@LiamDawe can you try again with version 0.9.1? I've just updated it in the AUR.

**Comment by sharkwouter** [comment]
I was finally able to reproduce this error and I found the cause. It should be fixed with commit eed0366b0498a624d109f16481662c9c2a16954f, which will be included in the next release.

**Comment by LiamDawe** [comment]
Ah great, nice work!

Give me another ping here when a release is out with it and I can give a thorough re-test :)

**Comment by sharkwouter** [comment]
@LiamDawe a new version has just been released and the AUR package was updated. Could you test to see if this issue was fixed?

**Comment by LiamDawe** [comment]
Yup, seems good now.

**Comment by sharkwouter** [comment]
Great! Thanks for confirming!
